DROP TABLE D2L_SURVEY_OBJECT_LOAD;
CREATE TABLE D2L_SURVEY_OBJECT_LOAD (
  SurveyId NUMBER(20) NOT NULL,
  SurveyName NVARCHAR2(1250) DEFAULT NULL,
  CategoryId NUMBER(20) DEFAULT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  Description NVARCHAR2(1250) DEFAULT NULL,
  DescriptionEnabled NUMBER(1) DEFAULT NULL,
  HasInstantFeedback NUMBER(1) DEFAULT NULL,
  IsAnonymous NUMBER(1) DEFAULT NULL,
  IsVisible NUMBER(1) DEFAULT NULL,
  SubmissionMessage NVARCHAR2(1250) DEFAULT NULL,
  Footer NVARCHAR2(1250) DEFAULT NULL,
  FooterIsDisplayed NUMBER(1) DEFAULT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  DisplayInCalendar NUMBER(1) DEFAULT NULL,
  ResultId NUMBER(20) DEFAULT NULL,
  AttemptsAllowed NUMBER(10) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  CategoryName NVARCHAR2(320) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SURVEY_OBJECT_LOAD_PK ON D2L_SURVEY_OBJECT_LOAD (SurveyId);
QUIT;
