DROP TABLE D2L_ASSIGNMENT_SPECIAL_ACCESS_LOAD;
CREATE TABLE D2L_ASSIGNMENT_SPECIAL_ACCESS_LOAD (
  DropboxId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  DueDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ModifiedBy NUMBER(10) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  StartDateAvailabilityType NUMBER(5) DEFAULT NULL,
  EndDateAvailabilityType NUMBER(5) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ASSIGNMENT_SPECIAL_ACCESS_LOAD_PK ON D2L_ASSIGNMENT_SPECIAL_ACCESS_LOAD (DropboxId,UserId);
QUIT;
