DROP TABLE D2L_CHECKLIST_CATEGORY_DETAIL_LOAD;
CREATE TABLE D2L_CHECKLIST_CATEGORY_DETAIL_LOAD (
  CategoryId NUMBER(20) NOT NULL,
  ChecklistId NUMBER(20) NOT NULL,
  Name NVARCHAR2(512) NOT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  DescriptionIsHtml NUMBER(1) NOT NULL,
  SortOrder NUMBER(10) NOT NULL,
  LastModifiedUtc DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHECKLIST_CATEGORY_DETAIL_LOAD_PK ON D2L_CHECKLIST_CATEGORY_DETAIL_LOAD (CategoryId);
QUIT;
