DROP TABLE D2L_SURVEY_OBJECT;
CREATE TABLE D2L_SURVEY_OBJECT (
  SurveyId NUMBER(20) NOT NULL,
  SurveyName NVARCHAR2(1000) NOT NULL,
  CategoryId NUMBER(20) DEFAULT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  DescriptionEnabled NUMBER(1) NOT NULL,
  HasInstantFeedback NUMBER(1) NOT NULL,
  IsAnonymous NUMBER(1) NOT NULL,
  IsVisible NUMBER(1) NOT NULL,
  SubmissionMessage NVARCHAR2(1000) DEFAULT NULL,
  Footer NVARCHAR2(1000) DEFAULT NULL,
  FooterIsDisplayed NUMBER(1) NOT NULL,
  StartDate DATE DEFAULT NULL,
  EndDate DATE DEFAULT NULL,
  DisplayInCalendar NUMBER(1) NOT NULL,
  ResultId NUMBER(20) DEFAULT NULL,
  AttemptsAllowed NUMBER(10) DEFAULT NULL,
  SortOrder NUMBER(10) NOT NULL,
  CreatedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  LastModified DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  Version NUMBER(20) NOT NULL,
  CategoryName NVARCHAR2(256) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SURVEY_OBJECT_PK ON D2L_SURVEY_OBJECT (SurveyId);
QUIT;
