DROP TABLE D2L_GRADE_SCHEME;
CREATE TABLE D2L_GRADE_SCHEME (
  GradeSchemeId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  SchemeName NVARCHAR2(128) NOT NULL,
  GradeSchemeRangeId NUMBER(20) NOT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  DeletedDate DATE DEFAULT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_GRADE_SCHEME_PK ON D2L_GRADE_SCHEME (GradeSchemeId,GradeSchemeRangeId);
QUIT;
