DROP TABLE D2L_OUTCOME_REGISTRY_OWNER;
CREATE TABLE D2L_OUTCOME_REGISTRY_OWNER (
  OwnerType NUMBER(10) NOT NULL,
  OwnerId NVARCHAR2(255) NOT NULL,
  RegistryId VARCHAR2(16) NOT NULL,
  CreatedDate DATE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOME_REGISTRY_OWNER_PK ON D2L_OUTCOME_REGISTRY_OWNER (OwnerType,OwnerId,RegistryId);
QUIT;
