DROP TABLE D2L_ACTIVITY_FEED_COMMENT_OBJECT;
CREATE TABLE D2L_ACTIVITY_FEED_COMMENT_OBJECT (
  OrgUnitId NUMBER(10) NOT NULL,
  CommentId VARCHAR2(16) NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  LastModified DATE NOT NULL,
  Content NVARCHAR2(3072) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  PostId VARCHAR2(16) NOT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_ACTIVITY_FEED_COMMENT_OBJECT_PK ON D2L_ACTIVITY_FEED_COMMENT_OBJECT (CommentId);
QUIT;
