DROP TABLE D2L_PORTFOLIO_CATEGORY_LOAD;
CREATE TABLE D2L_PORTFOLIO_CATEGORY_LOAD (
  CategoryId VARCHAR2(16) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  Name NVARCHAR2(256) NOT NULL,
  IsRetired NUMBER(1) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  LastModified DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_PORTFOLIO_CATEGORY_LOAD_PK ON D2L_PORTFOLIO_CATEGORY_LOAD (CategoryId);
QUIT;
