DROP TABLE D2L_ACTIVITY_FEED_COMMENT_LOG_LOAD;
CREATE TABLE D2L_ACTIVITY_FEED_COMMENT_LOG_LOAD (
  LogId VARCHAR2(16) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  CommentId VARCHAR2(16) NOT NULL,
  Action NVARCHAR2(16) NOT NULL,
  ActionDate DATE NOT NULL,
  Content NVARCHAR2(3072) NOT NULL,
  PostId VARCHAR2(16) NOT NULL
);
CREATE UNIQUE INDEX D2L_ACTIVITY_FEED_COMMENT_LOG_LOAD_PK ON D2L_ACTIVITY_FEED_COMMENT_LOG_LOAD (LogId);
QUIT;
