DROP TABLE D2L_GRADEBOOK_SETTING_LOAD;
CREATE TABLE D2L_GRADEBOOK_SETTING_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  GradeSchemeId NUMBER(20) NOT NULL,
  GradingSystem VARCHAR2(8) NOT NULL,
  UngradedItems VARCHAR2(25) NOT NULL,
  IsAdjustedFinalGradeReleased NUMBER(1) DEFAULT NULL,
  IsCalculatedFinalGradeReleased NUMBER(1) DEFAULT NULL,
  LastModified DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_GRADEBOOK_SETTING_LOAD_PK ON D2L_GRADEBOOK_SETTING_LOAD (OrgUnitId,GradeSchemeId);
QUIT;
