DROP TABLE D2L_ENROLLMENT_AND_WITHDRAWAL;
CREATE TABLE D2L_ENROLLMENT_AND_WITHDRAWAL (
  LogId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  RoleId NUMBER(10) DEFAULT NULL,
  Action VARCHAR2(50) NOT NULL,
  EnrollmentType VARCHAR2(50) DEFAULT NULL,
  ModifiedByUserId NUMBER(10) DEFAULT NULL,
  EnrollmentDate DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_ENROLLMENT_AND_WITHDRAWAL_PK ON D2L_ENROLLMENT_AND_WITHDRAWAL (LogId);
QUIT;
