DROP TABLE D2L_USER_ATTRIBUTE_DEFINITION_LOAD;
CREATE TABLE D2L_USER_ATTRIBUTE_DEFINITION_LOAD (
  AttributeId NVARCHAR2(128) NOT NULL,
  Name NVARCHAR2(128) NOT NULL,
  Type NVARCHAR2(8) NOT NULL,
  AllowMultiple NUMBER(1) NOT NULL,
  IsDefault NUMBER(1) NOT NULL,
  LastModified DATE NOT NULL,
  ModifiedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_USER_ATTRIBUTE_DEFINITION_LOAD_PK ON D2L_USER_ATTRIBUTE_DEFINITION_LOAD (AttributeId);
QUIT;
