DROP TABLE D2L_TURNITIN_SUBMISSION_LOAD;
CREATE TABLE D2L_TURNITIN_SUBMISSION_LOAD (
  DropboxId NUMBER(20) NOT NULL,
  SubmissionId NUMBER(20) NOT NULL,
  FileId NUMBER(20) NOT NULL,
  LastSubmissionDate DATE DEFAULT NULL,
  SubmissionStatus NUMBER(5) NOT NULL,
  SubmissionErrorType NUMBER(5) NOT NULL,
  ErrorMessage NVARCHAR2(255) DEFAULT NULL,
  SubmittedBy NUMBER(10) DEFAULT NULL,
  LastRefreshDate DATE DEFAULT NULL,
  LastModified DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_TURNITIN_SUBMISSION_LOAD_PK ON D2L_TURNITIN_SUBMISSION_LOAD (SubmissionId,FileId);
QUIT;
