DROP TABLE D2L_COMPETENCY_LOG_LOAD;
CREATE TABLE D2L_COMPETENCY_LOG_LOAD (
  CompetencyLogId NUMBER(20) NOT NULL,
  LogTypeId NUMBER(10) DEFAULT NULL,
  LogTypeName VARCHAR2(38 CHAR) DEFAULT NULL,
  ObjectId NUMBER(20) DEFAULT NULL,
  ObjectTypeId NUMBER(10) DEFAULT NULL,
  ObjectTypeName VARCHAR2(36 CHAR) DEFAULT NULL,
  ObjectVersion NUMBER(10) DEFAULT NULL,
  LogDateTime TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ModifiedBy NUMBER(20) DEFAULT NULL,
  IndirectObjectId NUMBER(20) DEFAULT NULL,
  IndirectObjectTypeName VARCHAR2(36 CHAR) DEFAULT NULL,
  IndirectObjectTypeId NUMBER(10) DEFAULT NULL,
  IndirectObjectVersion NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_COMPETENCY_LOG_LOAD_PK ON D2L_COMPETENCY_LOG_LOAD (CompetencyLogId);
QUIT;
