DROP TABLE D2L_AWARD_ISSUED;
CREATE TABLE D2L_AWARD_ISSUED (
  AwardId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(20) NOT NULL,
  UserId NUMBER(20) NOT NULL,
  Type NVARCHAR2(128) NOT NULL,
  IssuedBy NUMBER(10) NOT NULL,
  IssueDate DATE NOT NULL,
  ExpiryDate DATE DEFAULT NULL,
  IsRevoked NUMBER(1) NOT NULL,
  IssuedId NUMBER(20) NOT NULL,
  Credits NUMBER(9, 2) NOT NULL,
  Criteria NVARCHAR2(1000) DEFAULT NULL,
  Evidence NVARCHAR2(1000) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_AWARD_ISSUED_PK ON D2L_AWARD_ISSUED (IssuedId);
QUIT;
