DROP TABLE D2L_ACTIVITY_EXEMPTION_LOG;
CREATE TABLE D2L_ACTIVITY_EXEMPTION_LOG (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  ObjectId NUMBER(10) DEFAULT NULL,
  ActivityId VARCHAR2(225) NOT NULL,
  LogTypeName VARCHAR2(50) DEFAULT NULL,
  LastModifiedUtc DATE NOT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  ActivityExemptionsLogId NUMBER(20) NOT NULL,
  ToolId NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_ACTIVITY_EXEMPTION_LOG_PK ON D2L_ACTIVITY_EXEMPTION_LOG (ActivityExemptionsLogId);
QUIT;
