DROP TABLE D2L_USER_LOAD;
CREATE TABLE D2L_USER_LOAD (
  UserId NUMBER(10) NOT NULL,
  UserName NVARCHAR2(270) NOT NULL,
  OrgDefinedId NVARCHAR2(256) DEFAULT NULL,
  FirstName NVARCHAR2(64) NOT NULL,
  MiddleName NVARCHAR2(64) DEFAULT NULL,
  LastName NVARCHAR2(64) NOT NULL,
  IsActive NUMBER(1) DEFAULT NULL,
  Organization VARCHAR2(256) DEFAULT NULL,
  ExternalEmail NVARCHAR2(256) DEFAULT NULL,
  SignupDate DATE DEFAULT NULL,
  FirstLoginDate DATE DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  OrgRoleId NUMBER(10) DEFAULT NULL,
  LastAccessed DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_USER_LOAD_PK ON D2L_USER_LOAD (UserId);
QUIT;
