DROP TABLE D2L_DISCUSSION_TOPIC_USER_SCORE;
CREATE TABLE D2L_DISCUSSION_TOPIC_USER_SCORE (
  UserId NUMBER(10) NOT NULL,
  TopicId NUMBER(20) NOT NULL,
  Score DECIMAL(19, 9) DEFAULT NULL,
  IsGraded NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_DISCUSSION_TOPIC_USER_SCORE_PK ON D2L_DISCUSSION_TOPIC_USER_SCORE (UserId,TopicId);
QUIT;
