DROP TABLE D2L_LOCAL_AUTHENTICATION_SECURITY_LOG;
CREATE TABLE D2L_LOCAL_AUTHENTICATION_SECURITY_LOG (
  UserId NUMBER(10) NOT NULL,
  Action NVARCHAR2(87) NOT NULL,
  ModifiedBy NUMBER(10) NOT NULL,
  ModifiedDate TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX D2L_LOCAL_AUTHENTICATION_SECURITY_LOG_PK ON D2L_LOCAL_AUTHENTICATION_SECURITY_LOG (UserId,Action,ModifiedBy,ModifiedDate);
QUIT;
