DROP TABLE D2L_LTI_LINK_MIGRATION_AUDIT;
CREATE TABLE D2L_LTI_LINK_MIGRATION_AUDIT (
  LTIMigrationId VARCHAR2(16) NOT NULL,
  UserId NUMBER(20) NOT NULL,
  MigrationDate DATE NOT NULL,
  OrgUnitId NUMBER(20) NOT NULL,
  LinkId NUMBER(20) NOT NULL,
  LinkURL NVARCHAR2(2000) NOT NULL,
  LinkName NVARCHAR2(200) NOT NULL,
  ClientId NVARCHAR2(255) DEFAULT NULL,
  RegistrationDomain NVARCHAR2(2083) DEFAULT NULL,
  DeploymentId VARCHAR2(16) DEFAULT NULL,
  JobId NUMBER(20) NOT NULL,
  Status NUMBER(5) NOT NULL,
  FailureCode NUMBER(5) DEFAULT NULL,
  MigrationType NUMBER(5) NOT NULL
);
CREATE UNIQUE INDEX D2L_LTI_LINK_MIGRATION_AUDIT_PK ON D2L_LTI_LINK_MIGRATION_AUDIT (LTIMigrationId);
QUIT;
