DROP TABLE D2L_QUIZ_USER_ANSWER_LOAD;
CREATE TABLE D2L_QUIZ_USER_ANSWER_LOAD (
  AttemptId NUMBER(20) NOT NULL,
  QuestionId NUMBER(20) DEFAULT NULL,
  QuestionVersionId NUMBER(20) DEFAULT NULL,
  TimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  QuestionNumber NUMBER(10) DEFAULT NULL,
  D2LComment NVARCHAR2(1250) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  Score DECIMAL(19, 9) DEFAULT NULL,
  Page NUMBER(10) DEFAULT NULL,
  SectionId NUMBER(20) DEFAULT NULL,
  ObjectId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_USER_ANSWER_LOAD_PK ON D2L_QUIZ_USER_ANSWER_LOAD (AttemptId,ObjectId);
QUIT;
