DROP TABLE D2L_OUTCOMES_RUBRIC_ALIGNMENT;
CREATE TABLE D2L_OUTCOMES_RUBRIC_ALIGNMENT (
  RubricId NUMBER(20) NOT NULL,
  CriterionId NUMBER(20) NOT NULL,
  OutcomeId VARCHAR2(16) NOT NULL,
  RegistryId VARCHAR2(16) NOT NULL,
  CreatedDate DATE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_RUBRIC_ALIGNMENT_PK ON D2L_OUTCOMES_RUBRIC_ALIGNMENT (RubricId,CriterionId,OutcomeId,RegistryId);
QUIT;
