DROP TABLE D2L_COURSE_PUBLISHER_RECIPIENT_LOAD;
CREATE TABLE D2L_COURSE_PUBLISHER_RECIPIENT_LOAD (
  RecipientID VARCHAR2(36) NOT NULL,
  Name NVARCHAR2(512) DEFAULT NULL,
  CreatedAt TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_PUBLISHER_RECIPIENT_LOAD_PK ON D2L_COURSE_PUBLISHER_RECIPIENT_LOAD (RecipientID);
QUIT;
