DROP TABLE D2L_SCORM_ACTIVITY_ATTEMPT;
CREATE TABLE D2L_SCORM_ACTIVITY_ATTEMPT (
  VisitId VARCHAR2(16) NOT NULL,
  ActivityId VARCHAR2(16) NOT NULL,
  AttemptNumber NUMBER(10) NOT NULL,
  Completion NVARCHAR2(100) DEFAULT NULL,
  Success NVARCHAR2(100) DEFAULT NULL,
  Score FLOAT(24) DEFAULT NULL,
  ScoreRaw FLOAT(24) DEFAULT NULL,
  TimeSpent FLOAT(24) DEFAULT NULL,
  Progress FLOAT(24) DEFAULT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_ACTIVITY_ATTEMPT_PK ON D2L_SCORM_ACTIVITY_ATTEMPT (VisitId,ActivityId,AttemptNumber);
QUIT;
