DROP TABLE D2L_USER_LOGIN_LOAD;
CREATE TABLE D2L_USER_LOGIN_LOAD (
  OrgId NUMBER(10) DEFAULT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  UserName NVARCHAR2(256) NOT NULL,
  IP VARCHAR2(64) NOT NULL,
  SessionId NUMBER(10) DEFAULT NULL,
  StatusType VARCHAR2(50) NOT NULL,
  AttemptDate DATE NOT NULL,
  ImpersonatingUserId NUMBER(10) DEFAULT NULL,
  TimeOff NUMBER(10) DEFAULT NULL,
  LoginAttemptId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_USER_LOGIN_LOAD_PK ON D2L_USER_LOGIN_LOAD (LoginAttemptId);
QUIT;
