DROP TABLE D2L_SCORM_INTERACTION_ATTEMPT_LOAD;
CREATE TABLE D2L_SCORM_INTERACTION_ATTEMPT_LOAD (
  VisitId VARCHAR2(36) NOT NULL,
  InteractionId VARCHAR2(36) NOT NULL,
  AttemptNumber NUMBER(10) NOT NULL,
  ActivityId VARCHAR2(36) DEFAULT NULL,
  Timestamp TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Response NVARCHAR2(1250) DEFAULT NULL,
  Result NVARCHAR2(125) DEFAULT NULL,
  NumericResult FLOAT(24) DEFAULT NULL,
  TimeSpent FLOAT(24) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_INTERACTION_ATTEMPT_LOAD_PK ON D2L_SCORM_INTERACTION_ATTEMPT_LOAD (VisitId,InteractionId,AttemptNumber);
QUIT;
