DROP TABLE D2L_ACTIVITY_FEED_COMMENT_LOG_LOAD;
CREATE TABLE D2L_ACTIVITY_FEED_COMMENT_LOG_LOAD (
  LogId VARCHAR2(36) NOT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  CommentId VARCHAR2(36) DEFAULT NULL,
  Action NVARCHAR2(32) DEFAULT NULL,
  ActionDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Content NVARCHAR2(4000) DEFAULT NULL,
  PostId VARCHAR2(36) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ACTIVITY_FEED_COMMENT_LOG_LOAD_PK ON D2L_ACTIVITY_FEED_COMMENT_LOG_LOAD (LogId);
QUIT;
