DROP TABLE D2L_CONTENT_FILES_PROPERTY_LOG;
CREATE TABLE D2L_CONTENT_FILES_PROPERTY_LOG (
  OrgUnitId NUMBER(10) NOT NULL,
  ContentObjectId NUMBER(10) NOT NULL,
  Action NVARCHAR2(10) NOT NULL,
  FilePath NVARCHAR2(4000) NOT NULL,
  FileName NVARCHAR2(512) NOT NULL,
  FileExtension NVARCHAR2(512) NOT NULL,
  FileSizeBytes NUMBER(20) NOT NULL,
  UploadDate DATE NOT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_CONTENT_FILES_PROPERTY_LOG_PK ON D2L_CONTENT_FILES_PROPERTY_LOG (OrgUnitId,ContentObjectId,LastModified);
QUIT;
