DROP TABLE D2L_GRADE_SCHEME_RANGE;
CREATE TABLE D2L_GRADE_SCHEME_RANGE (
  GradeSchemeRangeId NUMBER(20) NOT NULL,
  GradeSchemeId NUMBER(20) NOT NULL,
  SymbolString NVARCHAR2(125) DEFAULT NULL,
  AssignedValue DECIMAL(19, 9) DEFAULT NULL,
  RangeStart DECIMAL(19, 9) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_GRADE_SCHEME_RANGE_PK ON D2L_GRADE_SCHEME_RANGE (GradeSchemeRangeId,GradeSchemeId);
QUIT;
