DROP TABLE D2L_ASSIGNMENT_SUBMISSION_DETAIL;
CREATE TABLE D2L_ASSIGNMENT_SUBMISSION_DETAIL (
  SubmissionId NUMBER(20) NOT NULL,
  DropboxId NUMBER(20) NOT NULL,
  UserId NUMBER(20) DEFAULT NULL,
  GroupId NUMBER(20) DEFAULT NULL,
  NumberOfFilesSubmitted NUMBER(10) DEFAULT NULL,
  TotalFileSize NUMBER(20) NOT NULL,
  SubmittedByUserId NUMBER(10) NOT NULL,
  DateSubmitted DATE DEFAULT NULL,
  Comments NVARCHAR2(1000) DEFAULT NULL,
  IsTurnItInExempt NUMBER(1) DEFAULT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  IsPreview NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_ASSIGNMENT_SUBMISSION_DETAIL_PK ON D2L_ASSIGNMENT_SUBMISSION_DETAIL (SubmissionId);
QUIT;
