DROP TABLE D2L_USER_ATTRIBUTE_DEFINITION_LOAD;
CREATE TABLE D2L_USER_ATTRIBUTE_DEFINITION_LOAD (
  AttributeId NVARCHAR2(256) NOT NULL,
  Name NVARCHAR2(256) DEFAULT NULL,
  Type NVARCHAR2(16) DEFAULT NULL,
  AllowMultiple NUMBER(1) DEFAULT NULL,
  IsDefault NUMBER(1) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ModifiedBy NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_USER_ATTRIBUTE_DEFINITION_LOAD_PK ON D2L_USER_ATTRIBUTE_DEFINITION_LOAD (AttributeId);
QUIT;
