DROP TABLE D2L_OUTCOMES_DEMONSTRATION;
CREATE TABLE D2L_OUTCOMES_DEMONSTRATION (
  DemonstrationId VARCHAR2(36) NOT NULL,
  ExplicitlyEnteredScaleLevelId VARCHAR2(36) DEFAULT NULL,
  AutomaticallyGeneratedScaleLevelId VARCHAR2(36) DEFAULT NULL,
  AlignedObjectType NUMBER(10) DEFAULT NULL,
  AlignedObjectId NVARCHAR2(2000) DEFAULT NULL,
  OutcomeId VARCHAR2(36) DEFAULT NULL,
  RegistryId VARCHAR2(36) DEFAULT NULL,
  IsPublished NUMBER(1) DEFAULT NULL,
  AssessedUserId NUMBER(10) DEFAULT NULL,
  AssessedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  AssessorUserId NUMBER(10) DEFAULT NULL,
  LastModifiedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_DEMONSTRATION_PK ON D2L_OUTCOMES_DEMONSTRATION (DemonstrationId);
QUIT;
