DROP TABLE D2L_COMPETENCY_LOG;
CREATE TABLE D2L_COMPETENCY_LOG (
  CompetencyLogId NUMBER(20) NOT NULL,
  LogTypeId NUMBER(10) NOT NULL,
  LogTypeName VARCHAR2(19) DEFAULT NULL,
  ObjectId NUMBER(20) NOT NULL,
  ObjectTypeId NUMBER(10) NOT NULL,
  ObjectTypeName VARCHAR2(18) DEFAULT NULL,
  ObjectVersion NUMBER(10) NOT NULL,
  LogDateTime DATE NOT NULL,
  ModifiedBy NUMBER(20) NOT NULL,
  IndirectObjectId NUMBER(20) DEFAULT NULL,
  IndirectObjectTypeName VARCHAR2(18) DEFAULT NULL,
  IndirectObjectTypeId NUMBER(10) DEFAULT NULL,
  IndirectObjectVersion NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_COMPETENCY_LOG_PK ON D2L_COMPETENCY_LOG (CompetencyLogId);
QUIT;
