DROP TABLE D2L_INTELLIGENT_AGENT_OBJECT;
CREATE TABLE D2L_INTELLIGENT_AGENT_OBJECT (
  AgentId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  AgentName NVARCHAR2(128) NOT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  Enabled NUMBER(1) NOT NULL,
  SpecificRoles NVARCHAR2(1000) DEFAULT NULL,
  LoginConditionEnabled NUMBER(1) NOT NULL,
  LoginConditionThreshold NUMBER(10) DEFAULT NULL,
  LoginConditionType NVARCHAR2(14) DEFAULT NULL,
  AccessConditionEnabled NUMBER(1) NOT NULL,
  AccessConditionThreshold NUMBER(10) DEFAULT NULL,
  AccessConditionType NVARCHAR2(20) DEFAULT NULL,
  ResultId NUMBER(20) DEFAULT NULL,
  RepeatType NVARCHAR2(10) NOT NULL,
  EmailWhenSatisfied NUMBER(1) NOT NULL,
  EnableSchedule NUMBER(1) NOT NULL,
  ScheduleType NVARCHAR2(8) DEFAULT NULL,
  ScheduleRepeatsEvery NUMBER(10) DEFAULT NULL,
  StartDate DATE DEFAULT NULL,
  EndDate DATE DEFAULT NULL,
  LastModified DATE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_INTELLIGENT_AGENT_OBJECT_PK ON D2L_INTELLIGENT_AGENT_OBJECT (AgentId);
QUIT;
