DROP TABLE D2L_QUIZ_USER_ANSWER;
CREATE TABLE D2L_QUIZ_USER_ANSWER (
  AttemptId NUMBER(20) NOT NULL,
  QuestionId NUMBER(20) NOT NULL,
  QuestionVersionId NUMBER(20) DEFAULT NULL,
  TimeCompleted DATE DEFAULT NULL,
  QuestionNumber NUMBER(10) DEFAULT NULL,
  D2LComment NVARCHAR2(1000) DEFAULT NULL,
  SortOrder NUMBER(10) NOT NULL,
  Score NUMBER(19, 9) DEFAULT NULL,
  Page NUMBER(10) NOT NULL,
  SectionId NUMBER(20) DEFAULT NULL,
  ObjectId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_USER_ANSWER_PK ON D2L_QUIZ_USER_ANSWER (AttemptId,ObjectId);
QUIT;
