DROP TABLE D2L_SCORM_ACTIVITY;
CREATE TABLE D2L_SCORM_ACTIVITY (
  ActivityId VARCHAR2(16) NOT NULL,
  ScormObjectId VARCHAR2(16) NOT NULL,
  ParentActivityId VARCHAR2(16) DEFAULT NULL,
  NumChildren NUMBER(10) NOT NULL,
  InternalId NVARCHAR2(255) DEFAULT NULL,
  Title NVARCHAR2(200) DEFAULT NULL,
  CompletionThreshold FLOAT(24) DEFAULT NULL,
  PassingScore FLOAT(24) DEFAULT NULL,
  PassingScoreUsed NUMBER(1) DEFAULT NULL,
  ScoreMin FLOAT(24) DEFAULT NULL,
  ScoreMax FLOAT(24) DEFAULT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_ACTIVITY_PK ON D2L_SCORM_ACTIVITY (ActivityId);
QUIT;
