DROP TABLE D2L_AWARD_OBJECT;
CREATE TABLE D2L_AWARD_OBJECT (
  AwardId NUMBER(20) NOT NULL,
  Name NVARCHAR2(256) NOT NULL,
  AwardTypeId NUMBER(10) NOT NULL,
  Type NVARCHAR2(128) NOT NULL,
  Description NVARCHAR2(512) NOT NULL,
  ExpiryCalculationType NVARCHAR2(128) NOT NULL,
  ExpiryNotificationType NVARCHAR2(128) NOT NULL,
  ExpiryDate DATE NOT NULL,
  ImagePath VARCHAR2(1000) DEFAULT NULL,
  CreatedByUserId NUMBER(20) NOT NULL,
  LastModified DATE NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  Criteria NVARCHAR2(1000) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_AWARD_OBJECT_PK ON D2L_AWARD_OBJECT (AwardId);
QUIT;
