DROP TABLE D2L_OUTCOMES_SCALE_LEVEL_DEFINITION;
CREATE TABLE D2L_OUTCOMES_SCALE_LEVEL_DEFINITION (
  ScaleLevelId VARCHAR2(36) NOT NULL,
  ScaleId VARCHAR2(36) DEFAULT NULL,
  Name NVARCHAR2(1250) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  PercentageRangeStart NUMBER(10) DEFAULT NULL,
  RGB NVARCHAR2(50) DEFAULT NULL,
  CreatedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_SCALE_LEVEL_DEFINITION_PK ON D2L_OUTCOMES_SCALE_LEVEL_DEFINITION (ScaleLevelId);
QUIT;
