DROP TABLE D2L_ORGANIZATIONAL_UNIT_LOAD;
CREATE TABLE D2L_ORGANIZATIONAL_UNIT_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  Organization NVARCHAR2(50) NOT NULL,
  Type NVARCHAR2(50) NOT NULL,
  Name NVARCHAR2(128) DEFAULT NULL,
  Code NVARCHAR2(50) DEFAULT NULL,
  StartDate DATE DEFAULT NULL,
  EndDate DATE DEFAULT NULL,
  IsActive NUMBER(1) NOT NULL,
  CreatedDate DATE NOT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  DeletedDate DATE DEFAULT NULL,
  RecycledDate DATE DEFAULT NULL,
  Version NUMBER(20) NOT NULL,
  OrgUnitTypeId NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_LOAD_PK ON D2L_ORGANIZATIONAL_UNIT_LOAD (OrgUnitId);
QUIT;
