DROP TABLE D2L_ORGANIZATIONAL_UNIT_PARENT;
CREATE TABLE D2L_ORGANIZATIONAL_UNIT_PARENT (
  OrgUnitId NUMBER(10) NOT NULL,
  ParentOrgUnitId NUMBER(10) NOT NULL,
  RowVersion NUMBER(20) NOT NULL,
  DateDeleted DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_PARENT_PK ON D2L_ORGANIZATIONAL_UNIT_PARENT (OrgUnitId,ParentOrgUnitId);
QUIT;
