DROP TABLE D2L_OUTCOMES_ASSESSED_CHECKPOINT_LOAD;
CREATE TABLE D2L_OUTCOMES_ASSESSED_CHECKPOINT_LOAD (
  CheckpointId VARCHAR2(36) NOT NULL,
  DemonstrationId VARCHAR2(36) NOT NULL,
  Feedback NVARCHAR2(1250) DEFAULT NULL,
  ConfigDecayRate NUMBER(10) DEFAULT NULL,
  ConfigAggregationMethod NUMBER(10) DEFAULT NULL,
  ConfigIncludedActivities NUMBER(10) DEFAULT NULL,
  ConfigMultipleAttemptStrategy NUMBER(10) DEFAULT NULL,
  ConfigRecentlyAssessedActivityCount NUMBER(10) DEFAULT NULL,
  ConfigTieBreaker NUMBER(10) DEFAULT NULL,
  LastModifiedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_ASSESSED_CHECKPOINT_LOAD_PK ON D2L_OUTCOMES_ASSESSED_CHECKPOINT_LOAD (CheckpointId,DemonstrationId);
QUIT;
