DROP TABLE D2L_TOOL_LOAD;
CREATE TABLE D2L_TOOL_LOAD (
  ToolId NUMBER(10) NOT NULL,
  Name NVARCHAR2(62) DEFAULT NULL,
  DisplayName NVARCHAR2(250) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_TOOL_LOAD_PK ON D2L_TOOL_LOAD (ToolId);
QUIT;
