DROP TABLE D2L_SCORM_VISIT;
CREATE TABLE D2L_SCORM_VISIT (
  VisitId VARCHAR2(36) NOT NULL,
  ScormObjectId VARCHAR2(36) DEFAULT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  FirstAccessDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastAccessDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  CompletedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Completion NVARCHAR2(125) DEFAULT NULL,
  Success NVARCHAR2(125) DEFAULT NULL,
  Score FLOAT(24) DEFAULT NULL,
  TimeSpent NUMBER(10) DEFAULT NULL,
  Progress FLOAT(24) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_VISIT_PK ON D2L_SCORM_VISIT (VisitId);
QUIT;
