DROP TABLE D2L_RELEASE_CONDITION_OBJECT;
CREATE TABLE D2L_RELEASE_CONDITION_OBJECT (
  PreRequisiteId NUMBER(10) NOT NULL,
  ResultId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  Name VARCHAR2(80 CHAR) DEFAULT NULL,
  IsNegativeCondition NUMBER(1) DEFAULT NULL,
  PreRequisiteToolId NUMBER(10) DEFAULT NULL,
  Id1 NUMBER(10) DEFAULT NULL,
  Id2 NUMBER(10) DEFAULT NULL,
  ResultToolId NUMBER(10) DEFAULT NULL,
  UsesPercentage NUMBER(1) DEFAULT NULL,
  OperatorTypeDesc VARCHAR2(3 CHAR) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_RELEASE_CONDITION_OBJECT_PK ON D2L_RELEASE_CONDITION_OBJECT (PreRequisiteId,ResultId,OrgUnitId);
QUIT;
