DROP TABLE D2L_SURVEY_QUESTION_ANSWER_OPTIONS_LOAD;
CREATE TABLE D2L_SURVEY_QUESTION_ANSWER_OPTIONS_LOAD (
  AnswerId NUMBER(20) NOT NULL,
  AnswerText NVARCHAR2(1000) DEFAULT NULL,
  Weight NUMBER(19, 9) NOT NULL,
  QuestionId NUMBER(20) NOT NULL,
  QuestionVersionId NUMBER(20) NOT NULL,
  SurveyObjectId NUMBER(20) NOT NULL,
  AnswerOptionId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_SURVEY_QUESTION_ANSWER_OPTIONS_LOAD_PK ON D2L_SURVEY_QUESTION_ANSWER_OPTIONS_LOAD (AnswerId,QuestionId,QuestionVersionId,SurveyObjectId,AnswerOptionId);
QUIT;
