DROP TABLE D2L_CHECKLIST_ITEM_DETAIL;
CREATE TABLE D2L_CHECKLIST_ITEM_DETAIL (
  ItemId NUMBER(20) NOT NULL,
  CategoryId NUMBER(20) DEFAULT NULL,
  Name NVARCHAR2(512) DEFAULT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  DescriptionIsHtml NUMBER(1) NOT NULL,
  DueDate DATE DEFAULT NULL,
  ScheduleId NUMBER(10) DEFAULT NULL,
  SortOrder NUMBER(10) NOT NULL,
  IsAutoChecked NUMBER(1) NOT NULL,
  LastModifiedUtc DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHECKLIST_ITEM_DETAIL_PK ON D2L_CHECKLIST_ITEM_DETAIL (ItemId);
QUIT;
