DROP TABLE D2L_QUIZ_ATTEMPT_LOAD;
CREATE TABLE D2L_QUIZ_ATTEMPT_LOAD (
  AttemptId NUMBER(20) NOT NULL,
  QuizId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  AttemptNumber NUMBER(10) NOT NULL,
  TimeStarted DATE NOT NULL,
  TimeCompleted DATE DEFAULT NULL,
  Score NUMBER(19, 9) DEFAULT NULL,
  IsGraded NUMBER(1) NOT NULL,
  OldAttemptNumber NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  PossibleScore NUMBER(19, 9) DEFAULT NULL,
  IsRetakeIncorrectOnly NUMBER(1) NOT NULL,
  DueDate DATE DEFAULT NULL,
  TimeLimit NUMBER(10) DEFAULT NULL,
  TimeLimitEnforced NUMBER(1) DEFAULT NULL,
  GracePeriod NUMBER(10) DEFAULT NULL,
  GracePeriodExceededBehaviour NVARCHAR2(128) DEFAULT NULL,
  ExtendedDeadline NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_ATTEMPT_LOAD_PK ON D2L_QUIZ_ATTEMPT_LOAD (AttemptId);
QUIT;
