DROP TABLE D2L_SURVEY_USER_ANSWER;
CREATE TABLE D2L_SURVEY_USER_ANSWER (
  AttemptId NUMBER(20) NOT NULL,
  QuestionId NUMBER(20) NOT NULL,
  QuestionVersionId NUMBER(20) NOT NULL,
  TimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  QuestionNumber NUMBER(10) DEFAULT NULL,
  D2LComment NVARCHAR2(1250) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  Score DECIMAL(19, 9) DEFAULT NULL,
  Page NUMBER(10) DEFAULT NULL,
  Assigned NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SURVEY_USER_ANSWER_PK ON D2L_SURVEY_USER_ANSWER (AttemptId,QuestionId,QuestionVersionId);
QUIT;
