DROP TABLE D2L_COMPETENCY_ACTIVITY_LOG_LOAD;
CREATE TABLE D2L_COMPETENCY_ACTIVITY_LOG_LOAD (
  ActivityId NUMBER(20) NOT NULL,
  ActivityLogId NUMBER(20) NOT NULL,
  LogTypeId NUMBER(10) NOT NULL,
  LogTypeName VARCHAR2(19) DEFAULT NULL,
  LogDateTime DATE NOT NULL,
  ModifiedBy NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_COMPETENCY_ACTIVITY_LOG_LOAD_PK ON D2L_COMPETENCY_ACTIVITY_LOG_LOAD (ActivityId,ActivityLogId);
QUIT;
