DROP TABLE D2L_RUBRIC_OBJECT_LOAD;
CREATE TABLE D2L_RUBRIC_OBJECT_LOAD (
  RubricId NUMBER(20) NOT NULL,
  Name NVARCHAR2(256) NOT NULL,
  RubricStatus NVARCHAR2(256) DEFAULT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  RubricType NVARCHAR2(256) DEFAULT NULL,
  ScoringMethods NVARCHAR2(256) DEFAULT NULL,
  IsScoreVisible NUMBER(1) NOT NULL,
  OrgUnitID NUMBER(10) NOT NULL,
  IsShared NUMBER(1) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_RUBRIC_OBJECT_LOAD_PK ON D2L_RUBRIC_OBJECT_LOAD (RubricId);
QUIT;
