DROP TABLE D2L_CHECKLIST_OBJECT;
CREATE TABLE D2L_CHECKLIST_OBJECT (
  ChecklistId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  Name NVARCHAR2(1024) DEFAULT NULL,
  Description NVARCHAR2(2000) DEFAULT NULL,
  DescriptionIsHtml NUMBER(1) DEFAULT NULL,
  SharedUserId NUMBER(10) DEFAULT NULL,
  DisplayInNewWindow NUMBER(1) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  ResultId NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHECKLIST_OBJECT_PK ON D2L_CHECKLIST_OBJECT (ChecklistId);
QUIT;
