DROP TABLE D2L_QUIZ_QUESTION_ANSWER_OPTION;
CREATE TABLE D2L_QUIZ_QUESTION_ANSWER_OPTION (
  AnswerId NUMBER(20) NOT NULL,
  AnswerText NVARCHAR2(1250) DEFAULT NULL,
  Weight DECIMAL(19, 9) DEFAULT NULL,
  QuestionId NUMBER(20) NOT NULL,
  QuestionVersionId NUMBER(20) NOT NULL,
  QuizObjectId NUMBER(20) NOT NULL,
  AnswerOptionId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_QUESTION_ANSWER_OPTION_PK ON D2L_QUIZ_QUESTION_ANSWER_OPTION (AnswerId,QuestionId,QuestionVersionId,QuizObjectId,AnswerOptionId);
QUIT;
