DROP TABLE D2L_LTI_LAUNCH_LOAD;
CREATE TABLE D2L_LTI_LAUNCH_LOAD (
  LTILaunchId VARCHAR2(16) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  IMSRoleNames NVARCHAR2(4000) NOT NULL,
  ImpersonatingUserId NUMBER(20) DEFAULT NULL,
  ImpersonatingUserIMSRoleName NVARCHAR2(4000) DEFAULT NULL,
  LaunchDate DATE NOT NULL,
  OrgUnitId NUMBER(20) NOT NULL,
  LTILinkId NUMBER(20) NOT NULL,
  DeploymentId VARCHAR2(16) DEFAULT NULL,
  ClientId VARCHAR2(16) DEFAULT NULL,
  ToolProviderId NVARCHAR2(300) DEFAULT NULL,
  ContentTopicId NUMBER(20) DEFAULT NULL,
  ParentModuleId NUMBER(20) DEFAULT NULL,
  Placement NVARCHAR2(10) DEFAULT NULL,
  MessageVersion NVARCHAR2(10) DEFAULT NULL,
  RequestType NVARCHAR2(30) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_LTI_LAUNCH_LOAD_PK ON D2L_LTI_LAUNCH_LOAD (LTILaunchId);
QUIT;
