DROP TABLE D2L_OUTCOMES_DEMONSTRATION_LOAD;
CREATE TABLE D2L_OUTCOMES_DEMONSTRATION_LOAD (
  DemonstrationId VARCHAR2(16) NOT NULL,
  ExplicitlyEnteredScaleLevelId VARCHAR2(16) DEFAULT NULL,
  AutomaticallyGeneratedScaleLevelId VARCHAR2(16) DEFAULT NULL,
  AlignedObjectType NUMBER(10) NOT NULL,
  AlignedObjectId NVARCHAR2(1000) NOT NULL,
  OutcomeId VARCHAR2(16) NOT NULL,
  RegistryId VARCHAR2(16) NOT NULL,
  IsPublished NUMBER(1) DEFAULT NULL,
  AssessedUserId NUMBER(10) NOT NULL,
  AssessedDate DATE NOT NULL,
  AssessorUserId NUMBER(10) DEFAULT NULL,
  LastModifiedDate DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_DEMONSTRATION_LOAD_PK ON D2L_OUTCOMES_DEMONSTRATION_LOAD (DemonstrationId);
QUIT;
