DROP TABLE D2L_DISCUSSION_TOPIC;
CREATE TABLE D2L_DISCUSSION_TOPIC (
  OrgUnitId NUMBER(10) NOT NULL,
  TopicId NUMBER(20) NOT NULL,
  ForumId NUMBER(20) NOT NULL,
  Name NVARCHAR2(1000) NOT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  MustPostToParticipate NUMBER(1) NOT NULL,
  AllowAnon NUMBER(1) NOT NULL,
  IsHidden NUMBER(1) NOT NULL,
  RequiresApproval NUMBER(1) NOT NULL,
  LastPostDate DATE DEFAULT NULL,
  LastPostUserId NUMBER(20) DEFAULT NULL,
  NumViews NUMBER(20) NOT NULL,
  SortOrder NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  DeletedDate DATE DEFAULT NULL,
  DeletedByUserId NUMBER(10) DEFAULT NULL,
  GradeItemId NUMBER(10) DEFAULT NULL,
  ScoreOutOf FLOAT(53) DEFAULT NULL,
  ScoreCalculationMethod VARCHAR2(19) NOT NULL,
  IncludeNonScoredValues NUMBER(1) NOT NULL,
  Version NUMBER(20) NOT NULL,
  ResultId NUMBER(10) DEFAULT NULL,
  StartDate DATE DEFAULT NULL,
  StartDateAvailabilityType NUMBER(5) DEFAULT NULL,
  EndDate DATE DEFAULT NULL,
  EndDateAvailabilityType NUMBER(5) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_DISCUSSION_TOPIC_PK ON D2L_DISCUSSION_TOPIC (TopicId);
QUIT;
