DROP TABLE D2L_SCORM_OBJECTIVE_LOAD;
CREATE TABLE D2L_SCORM_OBJECTIVE_LOAD (
  ObjectiveId VARCHAR2(36) NOT NULL,
  ScormObjectId VARCHAR2(36) DEFAULT NULL,
  ObjectiveType NVARCHAR2(125) DEFAULT NULL,
  ActivityId VARCHAR2(36) DEFAULT NULL,
  InternalId NVARCHAR2(318) DEFAULT NULL,
  IsPrimary NUMBER(1) DEFAULT NULL,
  Description NVARCHAR2(312) DEFAULT NULL,
  ScoreMin FLOAT(24) DEFAULT NULL,
  ScoreMax FLOAT(24) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_OBJECTIVE_LOAD_PK ON D2L_SCORM_OBJECTIVE_LOAD (ObjectiveId);
QUIT;
