DROP TABLE D2L_CALENDAR_EVENT;
CREATE TABLE D2L_CALENDAR_EVENT (
  ScheduleId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(20) DEFAULT NULL,
  UserId NUMBER(20) DEFAULT NULL,
  Title NVARCHAR2(320) DEFAULT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  TimeZoneIdentifier VARCHAR2(320 CHAR) DEFAULT NULL,
  IsAllDayEvent NUMBER(1) DEFAULT NULL,
  RecurrenceType VARCHAR2(8 CHAR) DEFAULT NULL,
  RecurrenceInterval NUMBER(10) DEFAULT NULL,
  CreatedByUserId NUMBER(10) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EventObjectTypeName NVARCHAR2(250) DEFAULT NULL,
  ObjectLookupId1 NUMBER(20) DEFAULT NULL,
  ObjectLookupId2 NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CALENDAR_EVENT_PK ON D2L_CALENDAR_EVENT (ScheduleId);
QUIT;
