DROP TABLE D2L_COURSE_AWARD_LOAD;
CREATE TABLE D2L_COURSE_AWARD_LOAD (
  AssociationId NUMBER(20) NOT NULL,
  AwardId NUMBER(20) DEFAULT NULL,
  OrgUnitId NUMBER(20) DEFAULT NULL,
  DateCreated TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  HiddenAward NUMBER(1) DEFAULT NULL,
  ConditionSetId NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_AWARD_LOAD_PK ON D2L_COURSE_AWARD_LOAD (AssociationId);
QUIT;
