DROP TABLE D2L_COMPETENCY_LOG;
CREATE TABLE D2L_COMPETENCY_LOG (
  CompetencyLogId NUMBER(20) NOT NULL,
  LogTypeId NUMBER(10) DEFAULT NULL,
  LogTypeName VARCHAR2(23 CHAR) DEFAULT NULL,
  ObjectId NUMBER(20) DEFAULT NULL,
  ObjectTypeId NUMBER(10) DEFAULT NULL,
  ObjectTypeName VARCHAR2(22 CHAR) DEFAULT NULL,
  ObjectVersion NUMBER(10) DEFAULT NULL,
  LogDateTime TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ModifiedBy NUMBER(20) DEFAULT NULL,
  IndirectObjectId NUMBER(20) DEFAULT NULL,
  IndirectObjectTypeName VARCHAR2(22 CHAR) DEFAULT NULL,
  IndirectObjectTypeId NUMBER(10) DEFAULT NULL,
  IndirectObjectVersion NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_COMPETENCY_LOG_PK ON D2L_COMPETENCY_LOG (CompetencyLogId);
QUIT;
