DROP TABLE D2L_COURSE_AWARD;
CREATE TABLE D2L_COURSE_AWARD (
  AssociationId NUMBER(20) NOT NULL,
  AwardId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(20) NOT NULL,
  DateCreated DATE NOT NULL,
  HiddenAward NUMBER(1) NOT NULL,
  ConditionSetId NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_AWARD_PK ON D2L_COURSE_AWARD (AssociationId);
QUIT;
