DROP TABLE D2L_COURSE_ACCESS_LOG;
CREATE TABLE D2L_COURSE_ACCESS_LOG (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  Timestamp DATE NOT NULL,
  Source NVARCHAR2(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_ACCESS_LOG_PK ON D2L_COURSE_ACCESS_LOG (OrgUnitId,UserId,Timestamp,Source);
QUIT;
