DROP TABLE D2L_OUTCOMES_SCALE_DEFINITION;
CREATE TABLE D2L_OUTCOMES_SCALE_DEFINITION (
  ScaleId VARCHAR2(16) NOT NULL,
  Name NVARCHAR2(1000) NOT NULL,
  IsDefault NUMBER(1) NOT NULL,
  UsePercentages NUMBER(1) NOT NULL,
  CreatedDate DATE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  RegistryId VARCHAR2(16) NOT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_SCALE_DEFINITION_PK ON D2L_OUTCOMES_SCALE_DEFINITION (ScaleId);
QUIT;
