DROP TABLE D2L_SCORM_OBJECTIVE_LOAD;
CREATE TABLE D2L_SCORM_OBJECTIVE_LOAD (
  ObjectiveId VARCHAR2(16) NOT NULL,
  ScormObjectId VARCHAR2(16) NOT NULL,
  ObjectiveType NVARCHAR2(100) NOT NULL,
  ActivityId VARCHAR2(16) DEFAULT NULL,
  InternalId NVARCHAR2(255) DEFAULT NULL,
  IsPrimary NUMBER(1) DEFAULT NULL,
  Description NVARCHAR2(250) DEFAULT NULL,
  ScoreMin FLOAT(24) DEFAULT NULL,
  ScoreMax FLOAT(24) DEFAULT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_OBJECTIVE_LOAD_PK ON D2L_SCORM_OBJECTIVE_LOAD (ObjectiveId);
QUIT;
