DROP TABLE D2L_USER_LOGIN_LOAD;
CREATE TABLE D2L_USER_LOGIN_LOAD (
  OrgId NUMBER(10) DEFAULT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  UserName NVARCHAR2(320) DEFAULT NULL,
  IP VARCHAR2(80 CHAR) DEFAULT NULL,
  SessionId NUMBER(10) DEFAULT NULL,
  StatusType VARCHAR2(62 CHAR) DEFAULT NULL,
  AttemptDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ImpersonatingUserId NUMBER(10) DEFAULT NULL,
  TimeOff NUMBER(10) DEFAULT NULL,
  LoginAttemptId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_USER_LOGIN_LOAD_PK ON D2L_USER_LOGIN_LOAD (LoginAttemptId);
QUIT;
