DROP TABLE D2L_QUIZ_QUESTION_ANSWER;
CREATE TABLE D2L_QUIZ_QUESTION_ANSWER (
  AnswerId NUMBER(20) NOT NULL,
  QuestionId NUMBER(20) NOT NULL,
  QuestionVersionId NUMBER(20) NOT NULL,
  SortOrder NUMBER(10) NOT NULL,
  IsCorrect NUMBER(1) DEFAULT NULL,
  Weight NUMBER(19, 9) DEFAULT NULL,
  Answer NVARCHAR2(1000) DEFAULT NULL,
  D2LComment NVARCHAR2(1000) DEFAULT NULL,
  Description NVARCHAR2(256) NOT NULL,
  ObjectId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_QUESTION_ANSWER_PK ON D2L_QUIZ_QUESTION_ANSWER (AnswerId,QuestionId,QuestionVersionId,ObjectId);
QUIT;
