DROP TABLE D2L_SYSTEM_ACCESS_LOG_LOAD;
CREATE TABLE D2L_SYSTEM_ACCESS_LOG_LOAD (
  SessionId NVARCHAR2(36) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  Timestamp DATE NOT NULL,
  State NVARCHAR2(20) NOT NULL,
  Source NVARCHAR2(20) NOT NULL,
  AppVersion NVARCHAR2(20) NOT NULL,
  Device NVARCHAR2(50) NOT NULL,
  IsOfflineMode NUMBER(1) NOT NULL,
  IPAddress NVARCHAR2(45) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SYSTEM_ACCESS_LOG_LOAD_PK ON D2L_SYSTEM_ACCESS_LOG_LOAD (SessionId,UserId,Timestamp,State);
QUIT;
