DROP TABLE D2L_VIRTUAL_CLASSROOM_USAGE;
CREATE TABLE D2L_VIRTUAL_CLASSROOM_USAGE (
  OrgUnitId NUMBER(10) NOT NULL,
  CourseName NVARCHAR2(255) NOT NULL,
  MeetingId NVARCHAR2(36) NOT NULL,
  MeetingName NVARCHAR2(255) NOT NULL,
  CreationUserId NUMBER(10) NOT NULL,
  CreationDate DATE NOT NULL,
  ScheduledDate DATE NOT NULL,
  ScheduledDuration NUMBER(10) NOT NULL,
  IsPublished NUMBER(1) NOT NULL,
  ExternalLinksEnabled NUMBER(1) NOT NULL,
  WholeClassInvited NUMBER(1) NOT NULL,
  IsCancelled NUMBER(1) NOT NULL,
  StartDateTime DATE NOT NULL,
  EndDateTime DATE NOT NULL,
  IsRecorded NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_VIRTUAL_CLASSROOM_USAGE_PK ON D2L_VIRTUAL_CLASSROOM_USAGE (MeetingId);
QUIT;
