DROP TABLE D2L_ACTIVITY_FEED_POST_LOG;
CREATE TABLE D2L_ACTIVITY_FEED_POST_LOG (
  LogId VARCHAR2(16) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  PostId VARCHAR2(16) NOT NULL,
  PostType NVARCHAR2(16) NOT NULL,
  Action NVARCHAR2(16) NOT NULL,
  ActionDate DATE NOT NULL,
  DropboxId NUMBER(20) DEFAULT NULL,
  Content NVARCHAR2(3072) DEFAULT NULL,
  CommentCount NUMBER(10) NOT NULL,
  AttachmentCount NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ACTIVITY_FEED_POST_LOG_PK ON D2L_ACTIVITY_FEED_POST_LOG (LogId);
QUIT;
