DROP TABLE D2L_CONTENT_USER_PROGRESS_LOAD;
CREATE TABLE D2L_CONTENT_USER_PROGRESS_LOAD (
  ContentObjectId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  CompletedDate DATE NOT NULL,
  LastVisited DATE DEFAULT NULL,
  IsRead NUMBER(1) NOT NULL,
  NumRealVisits NUMBER(10) NOT NULL,
  NumFakeVisits NUMBER(10) NOT NULL,
  TotalTime NUMBER(20) NOT NULL,
  IsVisited NUMBER(1) NOT NULL,
  IsCurrentBookmark NUMBER(1) NOT NULL,
  IsSelfAssessComplete NUMBER(1) NOT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_CONTENT_USER_PROGRESS_LOAD_PK ON D2L_CONTENT_USER_PROGRESS_LOAD (ContentObjectId,UserId);
QUIT;
