DROP TABLE D2L_CALENDAR_EVENT_LOAD;
CREATE TABLE D2L_CALENDAR_EVENT_LOAD (
  ScheduleId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(20) DEFAULT NULL,
  UserId NUMBER(20) DEFAULT NULL,
  Title NVARCHAR2(256) NOT NULL,
  StartDate DATE DEFAULT NULL,
  EndDate DATE DEFAULT NULL,
  TimeZoneIdentifier VARCHAR2(256) NOT NULL,
  IsAllDayEvent NUMBER(1) NOT NULL,
  RecurrenceType VARCHAR2(7) DEFAULT NULL,
  RecurrenceInterval NUMBER(10) NOT NULL,
  CreatedByUserId NUMBER(10) NOT NULL,
  LastModified DATE NOT NULL,
  EventObjectTypeName NVARCHAR2(200) DEFAULT NULL,
  ObjectLookupId1 NUMBER(20) DEFAULT NULL,
  ObjectLookupId2 NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CALENDAR_EVENT_LOAD_PK ON D2L_CALENDAR_EVENT_LOAD (ScheduleId);
QUIT;
