DROP TABLE D2L_SCORM_OBJECT;
CREATE TABLE D2L_SCORM_OBJECT (
  ScormObjectId VARCHAR2(36) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  ContentObjectId NUMBER(10) DEFAULT NULL,
  ContentServiceContentId VARCHAR2(36) DEFAULT NULL,
  ContentServiceRevisionId VARCHAR2(36) DEFAULT NULL,
  ContentServiceTopicId VARCHAR2(36) DEFAULT NULL,
  Title NVARCHAR2(1250) DEFAULT NULL,
  Description NVARCHAR2(1250) DEFAULT NULL,
  LearningStandard NVARCHAR2(125) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_OBJECT_PK ON D2L_SCORM_OBJECT (ScormObjectId);
QUIT;
