DROP TABLE D2L_DISCUSSION_TOPIC_USER_SCORE_LOAD;
CREATE TABLE D2L_DISCUSSION_TOPIC_USER_SCORE_LOAD (
  UserId NUMBER(10) NOT NULL,
  TopicId NUMBER(20) NOT NULL,
  Score NUMBER(19, 9) DEFAULT NULL,
  IsGraded NUMBER(1) NOT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_DISCUSSION_TOPIC_USER_SCORE_LOAD_PK ON D2L_DISCUSSION_TOPIC_USER_SCORE_LOAD (UserId,TopicId);
QUIT;
