DROP TABLE D2L_USER_ENROLLMENT;
CREATE TABLE D2L_USER_ENROLLMENT (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  RoleName NVARCHAR2(120) DEFAULT NULL,
  EnrollmentDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EnrollmentType VARCHAR2(100 CHAR) DEFAULT NULL,
  RoleId NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_USER_ENROLLMENT_PK ON D2L_USER_ENROLLMENT (OrgUnitId,UserId);
QUIT;
