DROP TABLE D2L_CHAT_SESSION_LOG;
CREATE TABLE D2L_CHAT_SESSION_LOG (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  ChatSessionId NUMBER(20) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE DEFAULT NULL,
  TimeSent DATE NOT NULL,
  MessageId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_CHAT_SESSION_LOG_PK ON D2L_CHAT_SESSION_LOG (MessageId);
QUIT;
