DROP TABLE D2L_USER;
CREATE TABLE D2L_USER (
  UserId NUMBER(10) NOT NULL,
  UserName NVARCHAR2(337) DEFAULT NULL,
  OrgDefinedId NVARCHAR2(320) DEFAULT NULL,
  FirstName NVARCHAR2(80) DEFAULT NULL,
  MiddleName NVARCHAR2(80) DEFAULT NULL,
  LastName NVARCHAR2(80) DEFAULT NULL,
  IsActive NUMBER(1) DEFAULT NULL,
  Organization VARCHAR2(320 CHAR) DEFAULT NULL,
  ExternalEmail NVARCHAR2(320) DEFAULT NULL,
  SignupDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  FirstLoginDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  OrgRoleId NUMBER(10) DEFAULT NULL,
  LastAccessed TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_USER_PK ON D2L_USER (UserId);
QUIT;
