DROP TABLE D2L_PORTFOLIO_EVIDENCE_CATEGORY;
CREATE TABLE D2L_PORTFOLIO_EVIDENCE_CATEGORY (
  CategoryId VARCHAR2(16) NOT NULL,
  EvidenceId VARCHAR2(16) NOT NULL,
  D2LGroup NVARCHAR2(30) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  LastModified DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_PORTFOLIO_EVIDENCE_CATEGORY_PK ON D2L_PORTFOLIO_EVIDENCE_CATEGORY (CategoryId,EvidenceId,D2LGroup);
QUIT;
