DROP TABLE D2L_AUDITOR_RELATIONSHIPS_LOG_LOAD;
CREATE TABLE D2L_AUDITOR_RELATIONSHIPS_LOG_LOAD (
  AuditorId NUMBER(10) NOT NULL,
  UserToAuditId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  Action NVARCHAR2(32) DEFAULT NULL,
  ModifiedBy NUMBER(10) DEFAULT NULL,
  ModifiedDate TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX D2L_AUDITOR_RELATIONSHIPS_LOG_LOAD_PK ON D2L_AUDITOR_RELATIONSHIPS_LOG_LOAD (AuditorId,UserToAuditId,OrgUnitId,ModifiedDate);
QUIT;
