DROP TABLE D2L_RUBRIC_EDIT;
CREATE TABLE D2L_RUBRIC_EDIT (
  AuditLogId VARCHAR2(16) NOT NULL,
  RubricId NUMBER(20) NOT NULL,
  CriterionId NUMBER(20) DEFAULT NULL,
  LevelId NUMBER(20) DEFAULT NULL,
  ModifiedBy NUMBER(10) NOT NULL,
  ModifiedObjectType NUMBER(10) NOT NULL,
  CriteriaGroupId NUMBER(20) DEFAULT NULL,
  ModifiedDate DATE NOT NULL,
  PreviousValue NVARCHAR2(4000) NOT NULL,
  ModifiedValue NVARCHAR2(4000) NOT NULL,
  IsLocked NUMBER(1) NOT NULL,
  Version NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_RUBRIC_EDIT_PK ON D2L_RUBRIC_EDIT (AuditLogId);
QUIT;
