DROP TABLE D2L_COMPETENCY_OBJECT_LOAD;
CREATE TABLE D2L_COMPETENCY_OBJECT_LOAD (
  ObjectId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  Name NVARCHAR2(256) NOT NULL,
  Type VARCHAR2(256) NOT NULL,
  ReadyForEvaluation NUMBER(1) NOT NULL,
  Status VARCHAR2(9) DEFAULT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  NeedReevaluation NUMBER(1) NOT NULL,
  ReevaluationIfAchieved NUMBER(1) DEFAULT NULL,
  ReevaluationIfNotAchieved NUMBER(1) DEFAULT NULL,
  AdditionalIdentifier NVARCHAR2(512) DEFAULT NULL,
  IsHidden NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_COMPETENCY_OBJECT_LOAD_PK ON D2L_COMPETENCY_OBJECT_LOAD (ObjectId);
QUIT;
