DROP TABLE D2L_PREREQUISITE_CONDITION_MET_LOAD;
CREATE TABLE D2L_PREREQUISITE_CONDITION_MET_LOAD (
  PreRequisiteId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  DateMet DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_PREREQUISITE_CONDITION_MET_LOAD_PK ON D2L_PREREQUISITE_CONDITION_MET_LOAD (PreRequisiteId,UserId);
QUIT;
