DROP TABLE D2L_QUIZ_ATTEMPT_LOG;
CREATE TABLE D2L_QUIZ_ATTEMPT_LOG (
  LogId NUMBER(20) NOT NULL,
  AttemptId NUMBER(20) NOT NULL,
  EventTypeId NUMBER(10) NOT NULL,
  Name NVARCHAR2(256) DEFAULT NULL,
  Description NVARCHAR2(256) DEFAULT NULL,
  EventTime DATE NOT NULL,
  IPAddress VARCHAR2(15) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_ATTEMPT_LOG_PK ON D2L_QUIZ_ATTEMPT_LOG (LogId);
QUIT;
