DROP TABLE D2L_AWARD_ISSUED;
CREATE TABLE D2L_AWARD_ISSUED (
  AwardId NUMBER(20) DEFAULT NULL,
  OrgUnitId NUMBER(20) DEFAULT NULL,
  UserId NUMBER(20) DEFAULT NULL,
  Type NVARCHAR2(160) DEFAULT NULL,
  IssuedBy NUMBER(10) DEFAULT NULL,
  IssueDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ExpiryDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsRevoked NUMBER(10) DEFAULT NULL,
  IssuedId NUMBER(20) NOT NULL,
  Credits DECIMAL(9, 2) DEFAULT NULL,
  Criteria NVARCHAR2(1250) DEFAULT NULL,
  Evidence NVARCHAR2(1250) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_AWARD_ISSUED_PK ON D2L_AWARD_ISSUED (IssuedId);
QUIT;
