DROP TABLE D2L_RUBRIC_OBJECT_LEVELS_LOAD;
CREATE TABLE D2L_RUBRIC_OBJECT_LEVELS_LOAD (
  RubricId NUMBER(20) DEFAULT NULL,
  LevelId NUMBER(20) NOT NULL,
  Name NVARCHAR2(320) DEFAULT NULL,
  Description NVARCHAR2(1250) DEFAULT NULL,
  Feedback NVARCHAR2(1250) DEFAULT NULL,
  Value DECIMAL(19, 9) DEFAULT NULL,
  RangeStartValue DECIMAL(19, 9) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  LevelSetId NUMBER(20) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_RUBRIC_OBJECT_LEVELS_LOAD_PK ON D2L_RUBRIC_OBJECT_LEVELS_LOAD (LevelId);
QUIT;
