DROP TABLE D2L_CHECKLIST_COMPLETION;
CREATE TABLE D2L_CHECKLIST_COMPLETION (
  UserId NUMBER(10) NOT NULL,
  DateCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ItemId NUMBER(20) NOT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHECKLIST_COMPLETION_PK ON D2L_CHECKLIST_COMPLETION (UserId,ItemId);
QUIT;
