DROP TABLE D2L_COURSE_COPY_LOG;
CREATE TABLE D2L_COURSE_COPY_LOG (
  SourceOrgUnitId NUMBER(10) NOT NULL,
  DestinationOrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(20) DEFAULT NULL,
  Status VARCHAR2(128) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE DEFAULT NULL,
  IsDestinationNew NUMBER(1) NOT NULL,
  CopyProtectedResources NUMBER(1) NOT NULL,
  CopyCourseJobId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_COPY_LOG_PK ON D2L_COURSE_COPY_LOG (CopyCourseJobId);
QUIT;
