DROP TABLE D2L_SCORM_INTERACTION_ATTEMPT;
CREATE TABLE D2L_SCORM_INTERACTION_ATTEMPT (
  VisitId VARCHAR2(16) NOT NULL,
  InteractionId VARCHAR2(16) NOT NULL,
  AttemptNumber NUMBER(10) NOT NULL,
  ActivityId VARCHAR2(16) NOT NULL,
  Timestamp DATE DEFAULT NULL,
  Response NVARCHAR2(1000) DEFAULT NULL,
  Result NVARCHAR2(100) DEFAULT NULL,
  NumericResult FLOAT(24) DEFAULT NULL,
  TimeSpent FLOAT(24) DEFAULT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_INTERACTION_ATTEMPT_PK ON D2L_SCORM_INTERACTION_ATTEMPT (VisitId,InteractionId,AttemptNumber);
QUIT;
