DROP TABLE D2L_TOOL;
CREATE TABLE D2L_TOOL (
  ToolId NUMBER(10) NOT NULL,
  Name NVARCHAR2(50) NOT NULL,
  DisplayName NVARCHAR2(200) NOT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_TOOL_PK ON D2L_TOOL (ToolId);
QUIT;
