DROP TABLE D2L_SURVEY_QUESTION_ANSWER_LOAD;
CREATE TABLE D2L_SURVEY_QUESTION_ANSWER_LOAD (
  AnswerId NUMBER(20) NOT NULL,
  QuestionId NUMBER(20) NOT NULL,
  QuestionVersionId NUMBER(20) NOT NULL,
  SortOrder NUMBER(10) NOT NULL,
  IsCorrect NUMBER(1) DEFAULT NULL,
  Weight NUMBER(19, 9) DEFAULT NULL,
  Answer NVARCHAR2(1000) DEFAULT NULL,
  D2LComment NVARCHAR2(1000) DEFAULT NULL,
  Description NVARCHAR2(256) NOT NULL,
  SurveyObjectId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_SURVEY_QUESTION_ANSWER_LOAD_PK ON D2L_SURVEY_QUESTION_ANSWER_LOAD (AnswerId,QuestionId,QuestionVersionId,SurveyObjectId);
QUIT;
