DROP TABLE D2L_RUBRIC_OBJECT_LOAD;
CREATE TABLE D2L_RUBRIC_OBJECT_LOAD (
  RubricId NUMBER(20) NOT NULL,
  Name NVARCHAR2(320) DEFAULT NULL,
  RubricStatus NVARCHAR2(320) DEFAULT NULL,
  Description NVARCHAR2(1250) DEFAULT NULL,
  RubricType NVARCHAR2(320) DEFAULT NULL,
  ScoringMethods NVARCHAR2(320) DEFAULT NULL,
  IsScoreVisible NUMBER(1) DEFAULT NULL,
  OrgUnitID NUMBER(10) DEFAULT NULL,
  IsShared NUMBER(1) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_RUBRIC_OBJECT_LOAD_PK ON D2L_RUBRIC_OBJECT_LOAD (RubricId);
QUIT;
