DROP TABLE D2L_SCORM_INTERACTION_OBJECTIVE;
CREATE TABLE D2L_SCORM_INTERACTION_OBJECTIVE (
  InteractionId VARCHAR2(16) NOT NULL,
  ObjectiveId VARCHAR2(16) NOT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_INTERACTION_OBJECTIVE_PK ON D2L_SCORM_INTERACTION_OBJECTIVE (InteractionId,ObjectiveId);
QUIT;
