DROP TABLE D2L_ATTENDANCE_REGISTER_LOAD;
CREATE TABLE D2L_ATTENDANCE_REGISTER_LOAD (
  AttendanceRegisterId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  Name NVARCHAR2(128) NOT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  SchemeId NUMBER(20) NOT NULL,
  IsVisible NUMBER(1) NOT NULL,
  IncludeAllUsers NUMBER(1) NOT NULL,
  CauseForConcern NUMBER(19, 9) DEFAULT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_ATTENDANCE_REGISTER_LOAD_PK ON D2L_ATTENDANCE_REGISTER_LOAD (AttendanceRegisterId);
QUIT;
