DROP TABLE D2L_OUTCOME_DETAIL_LOAD;
CREATE TABLE D2L_OUTCOME_DETAIL_LOAD (
  OutcomeId VARCHAR2(16) NOT NULL,
  OutcomeDefinitionSource NVARCHAR2(1000) NOT NULL,
  OutcomeDefinitionId NVARCHAR2(128) DEFAULT NULL,
  ParentOutcomeId VARCHAR2(16) DEFAULT NULL,
  Description NVARCHAR2(1000) NOT NULL,
  Notation NVARCHAR2(1000) NOT NULL,
  CreatedDate DATE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate DATE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOME_DETAIL_LOAD_PK ON D2L_OUTCOME_DETAIL_LOAD (OutcomeId);
QUIT;
