DROP TABLE D2L_ATTENDANCE_SCHEME;
CREATE TABLE D2L_ATTENDANCE_SCHEME (
  SchemeId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  SchemeName NVARCHAR2(128) NOT NULL,
  SchemeSymbolId NUMBER(20) NOT NULL,
  SymbolName NVARCHAR2(128) NOT NULL,
  SymbolValue NVARCHAR2(50) NOT NULL,
  Percentage NUMBER(19, 9) DEFAULT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_ATTENDANCE_SCHEME_PK ON D2L_ATTENDANCE_SCHEME (SchemeId,SchemeSymbolId);
QUIT;
