DROP TABLE D2L_RUBRIC_OBJECT_LEVELS;
CREATE TABLE D2L_RUBRIC_OBJECT_LEVELS (
  RubricId NUMBER(20) NOT NULL,
  LevelId NUMBER(20) NOT NULL,
  Name NVARCHAR2(256) NOT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  Feedback NVARCHAR2(1000) DEFAULT NULL,
  Value NUMBER(19, 9) DEFAULT NULL,
  RangeStartValue NUMBER(19, 9) DEFAULT NULL,
  SortOrder NUMBER(10) NOT NULL,
  LevelSetId NUMBER(20) NOT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_RUBRIC_OBJECT_LEVELS_PK ON D2L_RUBRIC_OBJECT_LEVELS (LevelId);
QUIT;
