DROP TABLE D2L_OUTCOMES_SCALE_LEVEL_DEFINITION_LOAD;
CREATE TABLE D2L_OUTCOMES_SCALE_LEVEL_DEFINITION_LOAD (
  ScaleLevelId VARCHAR2(16) NOT NULL,
  ScaleId VARCHAR2(16) NOT NULL,
  Name NVARCHAR2(1000) NOT NULL,
  SortOrder NUMBER(10) NOT NULL,
  PercentageRangeStart NUMBER(10) DEFAULT NULL,
  RGB NVARCHAR2(40) NOT NULL,
  CreatedDate DATE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_SCALE_LEVEL_DEFINITION_LOAD_PK ON D2L_OUTCOMES_SCALE_LEVEL_DEFINITION_LOAD (ScaleLevelId);
QUIT;
