DROP TABLE D2L_ATTENDANCE_SCHEME_LOAD;
CREATE TABLE D2L_ATTENDANCE_SCHEME_LOAD (
  SchemeId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  SchemeName NVARCHAR2(160) DEFAULT NULL,
  SchemeSymbolId NUMBER(20) NOT NULL,
  SymbolName NVARCHAR2(160) DEFAULT NULL,
  SymbolValue NVARCHAR2(62) DEFAULT NULL,
  Percentage DECIMAL(19, 9) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ATTENDANCE_SCHEME_LOAD_PK ON D2L_ATTENDANCE_SCHEME_LOAD (SchemeId,SchemeSymbolId);
QUIT;
