DROP TABLE D2L_RUBRIC_ASSESSMENT_CRITERIA_LOAD;
CREATE TABLE D2L_RUBRIC_ASSESSMENT_CRITERIA_LOAD (
  AssessmentId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  RubricId NUMBER(20) DEFAULT NULL,
  Score DECIMAL(19, 9) DEFAULT NULL,
  Feedback NVARCHAR2(2000) DEFAULT NULL,
  IsScoreOverridden NUMBER(1) DEFAULT NULL,
  CriterionId NUMBER(20) NOT NULL,
  LevelAchievedId NUMBER(20) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_RUBRIC_ASSESSMENT_CRITERIA_LOAD_PK ON D2L_RUBRIC_ASSESSMENT_CRITERIA_LOAD (AssessmentId,UserId,CriterionId);
QUIT;
