DROP TABLE D2L_USER_ATTRIBUTE_VALUE;
CREATE TABLE D2L_USER_ATTRIBUTE_VALUE (
  UserId NUMBER(10) NOT NULL,
  AttributeId NVARCHAR2(128) NOT NULL,
  Value NVARCHAR2(4000) NOT NULL,
  LastModified DATE NOT NULL,
  ModifiedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  Version NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_USER_ATTRIBUTE_VALUE_PK ON D2L_USER_ATTRIBUTE_VALUE (UserId,AttributeId);
QUIT;
