DROP TABLE D2L_ASSIGNMENT_SUBMISSION_LOAD;
CREATE TABLE D2L_ASSIGNMENT_SUBMISSION_LOAD (
  DropboxId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  SubmitterId NUMBER(20) NOT NULL,
  SubmitterType VARCHAR2(5) DEFAULT NULL,
  FileSubmissionCount NUMBER(10) NOT NULL,
  TotalFileSize NUMBER(20) NOT NULL,
  FeedbackUserId NUMBER(10) DEFAULT NULL,
  FeedbackIsRead NUMBER(1) NOT NULL,
  Score NUMBER(19, 9) DEFAULT NULL,
  IsGraded NUMBER(1) NOT NULL,
  LastSubmissionDate DATE DEFAULT NULL,
  Feedback NVARCHAR2(1000) DEFAULT NULL,
  FeedbackLastModified DATE DEFAULT NULL,
  FeedbackReadDate DATE DEFAULT NULL,
  CompletionDate DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ASSIGNMENT_SUBMISSION_LOAD_PK ON D2L_ASSIGNMENT_SUBMISSION_LOAD (DropboxId,SubmitterId);
QUIT;
