DROP TABLE D2L_JIT_PROVISIONED_USER_LOG_LOAD;
CREATE TABLE D2L_JIT_PROVISIONED_USER_LOG_LOAD (
  UserId NUMBER(10) NOT NULL,
  MappingField NVARCHAR2(40) DEFAULT NULL,
  MappingFieldValue NVARCHAR2(337) DEFAULT NULL,
  ProviderType NVARCHAR2(40) DEFAULT NULL,
  ProviderId NVARCHAR2(1280) DEFAULT NULL,
  RoleId NUMBER(10) DEFAULT NULL,
  Timestamp TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
  Action NVARCHAR2(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_JIT_PROVISIONED_USER_LOG_LOAD_PK ON D2L_JIT_PROVISIONED_USER_LOG_LOAD (UserId,Timestamp);
QUIT;
