DROP TABLE D2L_LTI_LINK_SHARED_LOAD;
CREATE TABLE D2L_LTI_LINK_SHARED_LOAD (
  OuAvailabilitySetId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  SharingType VARCHAR2(9) NOT NULL,
  DescendantTypeId NUMBER(10) DEFAULT NULL,
  LastModified DATE DEFAULT NULL
);
QUIT;
