DROP TABLE D2L_PORTFOLIO_EVIDENCE_OBJECT_LOAD;
CREATE TABLE D2L_PORTFOLIO_EVIDENCE_OBJECT_LOAD (
  EvidenceId VARCHAR2(16) NOT NULL,
  OwnerId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  EvidenceType NVARCHAR2(30) NOT NULL,
  Title NVARCHAR2(1000) NOT NULL,
  IsApproved NUMBER(1) NOT NULL,
  IsSpotlighted NUMBER(1) NOT NULL,
  IsSharedToParents NUMBER(1) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  IsRecoverableByInstructor NUMBER(1) DEFAULT NULL,
  LastModified DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  IsSharedWithInstructor NUMBER(1) DEFAULT NULL,
  DateSharedWithInstructor DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_PORTFOLIO_EVIDENCE_OBJECT_LOAD_PK ON D2L_PORTFOLIO_EVIDENCE_OBJECT_LOAD (EvidenceId);
QUIT;
