DROP TABLE D2L_USER_ENROLLMENT;
CREATE TABLE D2L_USER_ENROLLMENT (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  RoleName NVARCHAR2(60) NOT NULL,
  EnrollmentDate DATE NOT NULL,
  EnrollmentType VARCHAR2(50) DEFAULT NULL,
  RoleId NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_USER_ENROLLMENT_PK ON D2L_USER_ENROLLMENT (OrgUnitId,UserId);
QUIT;
