DROP TABLE D2L_QUIZ_SURVEY_SECTION;
CREATE TABLE D2L_QUIZ_SURVEY_SECTION (
  CollectionId NUMBER(20) NOT NULL,
  SectionId NUMBER(20) NOT NULL,
  Name NVARCHAR2(256) DEFAULT NULL,
  NameIsDisplayed NUMBER(1) NOT NULL,
  IsQuestionPool NUMBER(1) NOT NULL,
  SectionText NVARCHAR2(1000) DEFAULT NULL,
  SectionTextIsHTML NUMBER(1) NOT NULL,
  IsSectionTextHidden NUMBER(1) DEFAULT NULL,
  QuestionPoints NUMBER(19, 9) DEFAULT NULL,
  NumQuestions NUMBER(10) NOT NULL,
  NumChoices NUMBER(10) NOT NULL,
  Shuffle NUMBER(1) NOT NULL,
  CreationDate DATE NOT NULL,
  CreatedBy NUMBER(20) DEFAULT NULL,
  LastModified DATE NOT NULL,
  LastModifiedBy NUMBER(20) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_SURVEY_SECTION_PK ON D2L_QUIZ_SURVEY_SECTION (SectionId);
QUIT;
