DROP TABLE D2L_OUTCOMES_IN_REGISTRY_LOAD;
CREATE TABLE D2L_OUTCOMES_IN_REGISTRY_LOAD (
  OutcomeId VARCHAR2(36) NOT NULL,
  RegistryId VARCHAR2(36) NOT NULL,
  CreatedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_IN_REGISTRY_LOAD_PK ON D2L_OUTCOMES_IN_REGISTRY_LOAD (OutcomeId,RegistryId);
QUIT;
