DROP TABLE D2L_RELEASE_CONDITION_OBJECT_LOAD;
CREATE TABLE D2L_RELEASE_CONDITION_OBJECT_LOAD (
  PreRequisiteId NUMBER(10) NOT NULL,
  ResultId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  Name VARCHAR2(64) NOT NULL,
  IsNegativeCondition NUMBER(1) NOT NULL,
  PreRequisiteToolId NUMBER(10) NOT NULL,
  Id1 NUMBER(10) DEFAULT NULL,
  Id2 NUMBER(10) DEFAULT NULL,
  ResultToolId NUMBER(10) NOT NULL,
  UsesPercentage NUMBER(1) NOT NULL,
  OperatorTypeDesc VARCHAR2(3) DEFAULT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_RELEASE_CONDITION_OBJECT_LOAD_PK ON D2L_RELEASE_CONDITION_OBJECT_LOAD (PreRequisiteId,ResultId,OrgUnitId);
QUIT;
