DROP TABLE D2L_RUBRIC_ASSESSMENT_CRITERIA;
CREATE TABLE D2L_RUBRIC_ASSESSMENT_CRITERIA (
  AssessmentId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  RubricId NUMBER(20) NOT NULL,
  Score NUMBER(19, 9) DEFAULT NULL,
  Feedback NVARCHAR2(1000) DEFAULT NULL,
  IsScoreOverridden NUMBER(1) NOT NULL,
  CriterionId NUMBER(20) NOT NULL,
  LevelAchievedId NUMBER(20) DEFAULT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_RUBRIC_ASSESSMENT_CRITERIA_PK ON D2L_RUBRIC_ASSESSMENT_CRITERIA (AssessmentId,UserId,CriterionId);
QUIT;
