DROP TABLE D2L_ANNOUNCEMENT;
CREATE TABLE D2L_ANNOUNCEMENT (
  AnnouncementId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(20) NOT NULL,
  Title NVARCHAR2(400) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE DEFAULT NULL,
  IsGlobal NUMBER(1) NOT NULL,
  IsDraft NUMBER(1) NOT NULL,
  NumAttachments NUMBER(10) NOT NULL,
  DeletedDate DATE DEFAULT NULL,
  DeletedByUserId NUMBER(10) DEFAULT NULL,
  LastModified DATE NOT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  IsAuthorInfoShown NUMBER(1) NOT NULL,
  CreatedDate DATE DEFAULT NULL,
  ResultId NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ANNOUNCEMENT_PK ON D2L_ANNOUNCEMENT (AnnouncementId);
QUIT;
