DROP TABLE D2L_CHECKLIST_CATEGORY_DETAIL;
CREATE TABLE D2L_CHECKLIST_CATEGORY_DETAIL (
  CategoryId NUMBER(20) NOT NULL,
  ChecklistId NUMBER(20) DEFAULT NULL,
  Name NVARCHAR2(640) DEFAULT NULL,
  Description NVARCHAR2(1250) DEFAULT NULL,
  DescriptionIsHtml NUMBER(1) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  LastModifiedUtc TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHECKLIST_CATEGORY_DETAIL_PK ON D2L_CHECKLIST_CATEGORY_DETAIL (CategoryId);
QUIT;
