DROP TABLE D2L_GRADE_SCHEME_RANGE_LOAD;
CREATE TABLE D2L_GRADE_SCHEME_RANGE_LOAD (
  GradeSchemeRangeId NUMBER(20) NOT NULL,
  GradeSchemeId NUMBER(20) NOT NULL,
  SymbolString NVARCHAR2(100) NOT NULL,
  AssignedValue NUMBER(19, 9) DEFAULT NULL,
  RangeStart NUMBER(19, 9) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_GRADE_SCHEME_RANGE_LOAD_PK ON D2L_GRADE_SCHEME_RANGE_LOAD (GradeSchemeRangeId,GradeSchemeId);
QUIT;
