DROP TABLE D2L_USER_ENROLLMENT_LOAD;
CREATE TABLE D2L_USER_ENROLLMENT_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  RoleName NVARCHAR2(60) NOT NULL,
  EnrollmentDate DATE NOT NULL,
  EnrollmentType VARCHAR2(50) DEFAULT NULL,
  RoleId NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_USER_ENROLLMENT_LOAD_PK ON D2L_USER_ENROLLMENT_LOAD (OrgUnitId,UserId);
QUIT;
