DROP TABLE D2L_DISCUSSION_POST_READ_STATUS_LOAD;
CREATE TABLE D2L_DISCUSSION_POST_READ_STATUS_LOAD (
  TopicId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  PostId NUMBER(20) NOT NULL,
  IsRead NUMBER(1) NOT NULL,
  FirstReadDate DATE DEFAULT NULL,
  LastReadDate DATE DEFAULT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_DISCUSSION_POST_READ_STATUS_LOAD_PK ON D2L_DISCUSSION_POST_READ_STATUS_LOAD (UserId,PostId);
QUIT;
