DROP TABLE D2L_CHECKLIST_OBJECT_LOAD;
CREATE TABLE D2L_CHECKLIST_OBJECT_LOAD (
  ChecklistId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  Name NVARCHAR2(640) DEFAULT NULL,
  Description NVARCHAR2(1250) DEFAULT NULL,
  DescriptionIsHtml NUMBER(1) DEFAULT NULL,
  SharedUserId NUMBER(10) DEFAULT NULL,
  DisplayInNewWindow NUMBER(1) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  ResultId NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHECKLIST_OBJECT_LOAD_PK ON D2L_CHECKLIST_OBJECT_LOAD (ChecklistId);
QUIT;
