DROP TABLE D2L_TOOL_LOAD;
CREATE TABLE D2L_TOOL_LOAD (
  ToolId NUMBER(10) NOT NULL,
  Name NVARCHAR2(50) NOT NULL,
  DisplayName NVARCHAR2(200) NOT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_TOOL_LOAD_PK ON D2L_TOOL_LOAD (ToolId);
QUIT;
