DROP TABLE D2L_ORGANIZATIONAL_UNIT_LOAD;
CREATE TABLE D2L_ORGANIZATIONAL_UNIT_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  Organization NVARCHAR2(62) DEFAULT NULL,
  Type NVARCHAR2(62) DEFAULT NULL,
  Name NVARCHAR2(160) DEFAULT NULL,
  Code NVARCHAR2(62) DEFAULT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsActive NUMBER(1) DEFAULT NULL,
  CreatedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  DeletedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  RecycledDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  OrgUnitTypeId NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_LOAD_PK ON D2L_ORGANIZATIONAL_UNIT_LOAD (OrgUnitId);
QUIT;
