DROP TABLE D2L_SCORM_OBJECT;
CREATE TABLE D2L_SCORM_OBJECT (
  ScormObjectId VARCHAR2(16) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  ContentObjectId NUMBER(10) NOT NULL,
  ContentServiceContentId VARCHAR2(16) NOT NULL,
  ContentServiceRevisionId VARCHAR2(16) NOT NULL,
  ContentServiceTopicId VARCHAR2(16) NOT NULL,
  Title NVARCHAR2(1000) DEFAULT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  LearningStandard NVARCHAR2(100) DEFAULT NULL,
  LastModified DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_OBJECT_PK ON D2L_SCORM_OBJECT (ScormObjectId);
QUIT;
