DROP TABLE D2L_COMPETENCY_ACTIVITY_LOAD;
CREATE TABLE D2L_COMPETENCY_ACTIVITY_LOAD (
  ActivityId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  ActivityName NVARCHAR2(512) DEFAULT NULL,
  ActivityTypeId NUMBER(10) DEFAULT NULL,
  AssessmentType VARCHAR2(14 CHAR) DEFAULT NULL,
  ObjectLookupId NUMBER(20) DEFAULT NULL,
  RubricId NUMBER(20) DEFAULT NULL,
  LevelId NUMBER(20) DEFAULT NULL,
  RubricCriterionId NUMBER(20) DEFAULT NULL,
  AssessmentThresholdCriteria VARCHAR2(4 CHAR) DEFAULT NULL,
  AssessmentThreshold DECIMAL(19, 9) DEFAULT NULL,
  IsAutoEval NUMBER(1) DEFAULT NULL,
  RubricName NVARCHAR2(512) DEFAULT NULL,
  RubricLevelRequired NVARCHAR2(512) DEFAULT NULL,
  ObjectId NUMBER(20) DEFAULT NULL,
  ActivityType NVARCHAR2(100) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_COMPETENCY_ACTIVITY_LOAD_PK ON D2L_COMPETENCY_ACTIVITY_LOAD (ActivityId);
QUIT;
