DROP TABLE D2L_COMPETENCY_ACTIVITY_LOAD;
CREATE TABLE D2L_COMPETENCY_ACTIVITY_LOAD (
  ActivityId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  ActivityName NVARCHAR2(256) NOT NULL,
  ActivityTypeId NUMBER(10) NOT NULL,
  AssessmentType VARCHAR2(7) NOT NULL,
  ObjectLookupId NUMBER(20) NOT NULL,
  RubricId NUMBER(20) DEFAULT NULL,
  LevelId NUMBER(20) DEFAULT NULL,
  RubricCriterionId NUMBER(20) NOT NULL,
  AssessmentThresholdCriteria VARCHAR2(2) DEFAULT NULL,
  AssessmentThreshold NUMBER(19, 9) DEFAULT NULL,
  IsAutoEval NUMBER(1) NOT NULL,
  RubricName NVARCHAR2(256) DEFAULT NULL,
  RubricLevelRequired NVARCHAR2(256) DEFAULT NULL,
  ObjectId NUMBER(20) DEFAULT NULL,
  ActivityType NVARCHAR2(50) DEFAULT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_COMPETENCY_ACTIVITY_LOAD_PK ON D2L_COMPETENCY_ACTIVITY_LOAD (ActivityId);
QUIT;
