DROP TABLE D2L_ATTENDANCE_USER_SESSION;
CREATE TABLE D2L_ATTENDANCE_USER_SESSION (
  UserId NUMBER(10) NOT NULL,
  AttendanceSessionId NUMBER(20) NOT NULL,
  SchemeSymbolId NUMBER(20) NOT NULL,
  LastModified DATE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ATTENDANCE_USER_SESSION_PK ON D2L_ATTENDANCE_USER_SESSION (UserId,AttendanceSessionId);
QUIT;
