DROP TABLE D2L_SCORM_VISIT_LOAD;
CREATE TABLE D2L_SCORM_VISIT_LOAD (
  VisitId VARCHAR2(16) NOT NULL,
  ScormObjectId VARCHAR2(16) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  FirstAccessDate DATE DEFAULT NULL,
  LastAccessDate DATE DEFAULT NULL,
  CompletedDate DATE DEFAULT NULL,
  Completion NVARCHAR2(100) DEFAULT NULL,
  Success NVARCHAR2(100) DEFAULT NULL,
  Score FLOAT(24) DEFAULT NULL,
  TimeSpent NUMBER(10) DEFAULT NULL,
  Progress FLOAT(24) DEFAULT NULL,
  LastModified DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SCORM_VISIT_LOAD_PK ON D2L_SCORM_VISIT_LOAD (VisitId);
QUIT;
