DROP TABLE D2L_ORGANIZATIONAL_UNIT_RECENT_ACCESS_LOAD;
CREATE TABLE D2L_ORGANIZATIONAL_UNIT_RECENT_ACCESS_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  LastAccessedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_RECENT_ACCESS_LOAD_PK ON D2L_ORGANIZATIONAL_UNIT_RECENT_ACCESS_LOAD (OrgUnitId,UserId);
QUIT;
