DROP TABLE D2L_CONTENT_OBJECT_LOAD;
CREATE TABLE D2L_CONTENT_OBJECT_LOAD (
  ContentObjectId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  Title NVARCHAR2(150) NOT NULL,
  ContentObjectType VARCHAR2(6) NOT NULL,
  CompletionType VARCHAR2(7) NOT NULL,
  ParentContentObjectId NUMBER(10) NOT NULL,
  Location NVARCHAR2(1024) DEFAULT NULL,
  StartDate DATE DEFAULT NULL,
  EndDate DATE DEFAULT NULL,
  DueDate DATE DEFAULT NULL,
  ObjectId1 NUMBER(10) DEFAULT NULL,
  ObjectId2 NUMBER(10) DEFAULT NULL,
  ObjectId3 NUMBER(10) DEFAULT NULL,
  LastModified DATE NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  SortOrder NUMBER(10) NOT NULL,
  Depth NUMBER(10) NOT NULL,
  ToolId NUMBER(10) DEFAULT NULL,
  IsHidden NUMBER(1) NOT NULL,
  ResultId NUMBER(10) DEFAULT NULL,
  DeletedDate DATE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  DeletedBy NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CONTENT_OBJECT_LOAD_PK ON D2L_CONTENT_OBJECT_LOAD (ContentObjectId);
QUIT;
