DROP TABLE D2L_ASSIGNMENT_SPECIAL_ACCESS;
CREATE TABLE D2L_ASSIGNMENT_SPECIAL_ACCESS (
  DropboxId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  StartDate DATE DEFAULT NULL,
  EndDate DATE DEFAULT NULL,
  DueDate DATE DEFAULT NULL,
  ModifiedBy NUMBER(10) NOT NULL,
  LastModified DATE NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  StartDateAvailabilityType NUMBER(5) DEFAULT NULL,
  EndDateAvailabilityType NUMBER(5) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ASSIGNMENT_SPECIAL_ACCESS_PK ON D2L_ASSIGNMENT_SPECIAL_ACCESS (DropboxId,UserId);
QUIT;
