DROP TABLE D2L_ASSIGNMENT_SUMMARY;
CREATE TABLE D2L_ASSIGNMENT_SUMMARY (
  DropboxId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  Name NVARCHAR2(256) DEFAULT NULL,
  Category NVARCHAR2(256) DEFAULT NULL,
  Type VARCHAR2(20 CHAR) DEFAULT NULL,
  GradeItemId NUMBER(20) DEFAULT NULL,
  PossibleScore DECIMAL(19, 9) DEFAULT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  DueDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  IsRestricted NUMBER(1) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  TurnItInEnabled NUMBER(1) DEFAULT NULL,
  IsHidden NUMBER(1) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  SubmissionType VARCHAR2(36 CHAR) DEFAULT NULL,
  CompletionType VARCHAR2(54 CHAR) DEFAULT NULL,
  ResultId NUMBER(10) DEFAULT NULL,
  CategoryId NUMBER(20) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  StartDateAvailabilityType NUMBER(5) DEFAULT NULL,
  EndDateAvailabilityType NUMBER(5) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ASSIGNMENT_SUMMARY_PK ON D2L_ASSIGNMENT_SUMMARY (DropboxId);
QUIT;
