DROP TABLE D2L_COURSE_PUBLISHER_LAUNCH_LOAD;
CREATE TABLE D2L_COURSE_PUBLISHER_LAUNCH_LOAD (
  LaunchId VARCHAR2(16) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  RecipientId VARCHAR2(16) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  RoleId NUMBER(10) NOT NULL,
  LaunchMethod NVARCHAR2(256) NOT NULL,
  ExternalUserId NVARCHAR2(256) NOT NULL,
  ExternalLMSType NVARCHAR2(256) NOT NULL,
  IsNewUser NUMBER(1) NOT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_PUBLISHER_LAUNCH_LOAD_PK ON D2L_COURSE_PUBLISHER_LAUNCH_LOAD (LaunchId);
QUIT;
