DROP TABLE D2L_DISCUSSION_POST_LOAD;
CREATE TABLE D2L_DISCUSSION_POST_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  TopicId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  PostId NUMBER(20) NOT NULL,
  ThreadId NUMBER(20) NOT NULL,
  IsReply NUMBER(1) NOT NULL,
  ParentPostId NUMBER(20) DEFAULT NULL,
  NumReplies NUMBER(10) NOT NULL,
  DatePosted DATE NOT NULL,
  IsDeleted NUMBER(1) NOT NULL,
  RatingSum NUMBER(20) NOT NULL,
  NumRatings NUMBER(20) NOT NULL,
  Score NUMBER(19, 9) DEFAULT NULL,
  LastEditDate DATE DEFAULT NULL,
  SortOrder NUMBER(10) NOT NULL,
  Depth NUMBER(10) NOT NULL,
  Thread NVARCHAR2(400) DEFAULT NULL,
  WordCount NUMBER(10) DEFAULT NULL,
  AttachmentCount NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_DISCUSSION_POST_LOAD_PK ON D2L_DISCUSSION_POST_LOAD (PostId);
QUIT;
