DROP TABLE D2L_CHAT_OBJECT;
CREATE TABLE D2L_CHAT_OBJECT (
  ChatId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  ChatType NVARCHAR2(128) DEFAULT NULL,
  Name NVARCHAR2(150) NOT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  CreatorUserId NUMBER(10) NOT NULL,
  LastModified DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHAT_OBJECT_PK ON D2L_CHAT_OBJECT (ChatId);
QUIT;
