DROP TABLE D2L_SURVEY_ATTEMPT_LOAD;
CREATE TABLE D2L_SURVEY_ATTEMPT_LOAD (
  AttemptId NUMBER(20) NOT NULL,
  SurveyId NUMBER(20) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  AttemptNumber NUMBER(10) NOT NULL,
  TimeStarted DATE NOT NULL,
  TimeCompleted DATE DEFAULT NULL,
  AttemptedFromOrgUnitId NUMBER(10) DEFAULT NULL,
  OldAttemptNumber NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_SURVEY_ATTEMPT_LOAD_PK ON D2L_SURVEY_ATTEMPT_LOAD (AttemptId);
QUIT;
