DROP TABLE D2L_QUIZ_SURVEY_SECTION;
CREATE TABLE D2L_QUIZ_SURVEY_SECTION (
  CollectionId NUMBER(20) DEFAULT NULL,
  SectionId NUMBER(20) NOT NULL,
  Name NVARCHAR2(320) DEFAULT NULL,
  NameIsDisplayed NUMBER(1) DEFAULT NULL,
  IsQuestionPool NUMBER(1) DEFAULT NULL,
  SectionText NVARCHAR2(1250) DEFAULT NULL,
  SectionTextIsHTML NUMBER(1) DEFAULT NULL,
  IsSectionTextHidden NUMBER(1) DEFAULT NULL,
  QuestionPoints DECIMAL(19, 9) DEFAULT NULL,
  NumQuestions NUMBER(10) DEFAULT NULL,
  NumChoices NUMBER(10) DEFAULT NULL,
  Shuffle NUMBER(1) DEFAULT NULL,
  CreationDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  CreatedBy NUMBER(20) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(20) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_SURVEY_SECTION_PK ON D2L_QUIZ_SURVEY_SECTION (SectionId);
QUIT;
