DROP TABLE D2L_OUTCOMES_PROGRAM_DETAIL_LOAD;
CREATE TABLE D2L_OUTCOMES_PROGRAM_DETAIL_LOAD (
  ProgramId NUMBER(20) NOT NULL,
  ProgramName NVARCHAR2(1250) DEFAULT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  CreatedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_PROGRAM_DETAIL_LOAD_PK ON D2L_OUTCOMES_PROGRAM_DETAIL_LOAD (ProgramId);
QUIT;
