DROP TABLE D2L_COURSE_ACCESS_LOG_LOAD;
CREATE TABLE D2L_COURSE_ACCESS_LOG_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  UserId NUMBER(10) NOT NULL,
  Timestamp DATE NOT NULL,
  Source NVARCHAR2(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_ACCESS_LOG_LOAD_PK ON D2L_COURSE_ACCESS_LOG_LOAD (OrgUnitId,UserId,Timestamp,Source);
QUIT;
