DROP TABLE D2L_OUTCOMES_PROGRAM_DETAIL_LOAD;
CREATE TABLE D2L_OUTCOMES_PROGRAM_DETAIL_LOAD (
  ProgramId NUMBER(20) NOT NULL,
  ProgramName NVARCHAR2(1000) NOT NULL,
  OrgUnitId NUMBER(10) NOT NULL,
  CreatedDate DATE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_PROGRAM_DETAIL_LOAD_PK ON D2L_OUTCOMES_PROGRAM_DETAIL_LOAD (ProgramId);
QUIT;
