DROP TABLE D2L_GRADE_SCHEME;
CREATE TABLE D2L_GRADE_SCHEME (
  GradeSchemeId NUMBER(20) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  SchemeName NVARCHAR2(256) DEFAULT NULL,
  GradeSchemeRangeId NUMBER(20) NOT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  DeletedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_GRADE_SCHEME_PK ON D2L_GRADE_SCHEME (GradeSchemeId,GradeSchemeRangeId);
QUIT;
