DROP TABLE D2L_DISCUSSION_FORUM_LOAD;
CREATE TABLE D2L_DISCUSSION_FORUM_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  ForumId NUMBER(20) NOT NULL,
  Name NVARCHAR2(400) NOT NULL,
  Description NVARCHAR2(1000) DEFAULT NULL,
  MustPostToParticipate NUMBER(1) NOT NULL,
  AllowAnon NUMBER(1) NOT NULL,
  IsHidden NUMBER(1) NOT NULL,
  RequiresApproval NUMBER(1) NOT NULL,
  SortOrder NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  DeletedDate DATE DEFAULT NULL,
  DeletedByUserId NUMBER(10) DEFAULT NULL,
  ResultId NUMBER(10) DEFAULT NULL,
  StartDate DATE DEFAULT NULL,
  StartDateAvailabilityType NUMBER(5) DEFAULT NULL,
  EndDate DATE NOT NULL,
  EndDateAvailabilityType NUMBER(5) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_DISCUSSION_FORUM_LOAD_PK ON D2L_DISCUSSION_FORUM_LOAD (ForumId);
QUIT;
