DROP TABLE D2L_CHECKLIST_COMPLETION;
CREATE TABLE D2L_CHECKLIST_COMPLETION (
  UserId NUMBER(10) NOT NULL,
  DateCompleted DATE NOT NULL,
  ItemId NUMBER(20) NOT NULL,
  LastModified DATE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHECKLIST_COMPLETION_PK ON D2L_CHECKLIST_COMPLETION (UserId,ItemId);
QUIT;
