DROP TABLE D2L_COURSE_PUBLISHER_RECIPIENT_LOAD;
CREATE TABLE D2L_COURSE_PUBLISHER_RECIPIENT_LOAD (
  RecipientID VARCHAR2(16) NOT NULL,
  Name NVARCHAR2(256) NOT NULL,
  CreatedAt DATE NOT NULL,
  LastModified DATE NOT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_PUBLISHER_RECIPIENT_LOAD_PK ON D2L_COURSE_PUBLISHER_RECIPIENT_LOAD (RecipientID);
QUIT;
