DROP TABLE D2L_OUTCOMES_ALIGNED_TO_TOOL_OBJECT;
CREATE TABLE D2L_OUTCOMES_ALIGNED_TO_TOOL_OBJECT (
  ObjectType NUMBER(10) NOT NULL,
  ObjectId NVARCHAR2(255) NOT NULL,
  OutcomeId VARCHAR2(16) NOT NULL,
  RegistryId VARCHAR2(16) NOT NULL,
  CreatedDate DATE DEFAULT NULL,
  CreatedBy NUMBER(10) DEFAULT NULL,
  LastModifiedDate DATE NOT NULL,
  LastModifiedBy NUMBER(10) NOT NULL,
  IsDeleted NUMBER(1) NOT NULL
);
CREATE UNIQUE INDEX D2L_OUTCOMES_ALIGNED_TO_TOOL_OBJECT_PK ON D2L_OUTCOMES_ALIGNED_TO_TOOL_OBJECT (ObjectType,ObjectId,OutcomeId,RegistryId);
QUIT;
