DROP TABLE IF EXISTS `ActivityFeedPostLog`;

CREATE TABLE `ActivityFeedPostLog` (
  `LogId` VARCHAR(36) NOT NULL,
  `UserId` INT DEFAULT NULL,
  `OrgUnitId` INT DEFAULT NULL,
  `PostId` VARCHAR(36) DEFAULT NULL,
  `PostType` VARCHAR(16) DEFAULT NULL,
  `Action` VARCHAR(16) DEFAULT NULL,
  `ActionDate` DATETIME DEFAULT NULL,
  `DropboxId` BIGINT DEFAULT NULL,
  `Content` VARCHAR(3072) DEFAULT NULL,
  `CommentCount` INT DEFAULT NULL,
  `AttachmentCount` INT DEFAULT NULL,
  UNIQUE KEY (`LogId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
