DROP TABLE IF EXISTS `ContentObject_LOAD`;

CREATE TABLE `ContentObject_LOAD` (
  `ContentObjectId` INT NOT NULL,
  `OrgUnitId` INT DEFAULT NULL,
  `Title` VARCHAR(150) DEFAULT NULL,
  `ContentObjectType` VARCHAR(6) DEFAULT NULL,
  `CompletionType` VARCHAR(7) DEFAULT NULL,
  `ParentContentObjectId` INT DEFAULT NULL,
  `Location` VARCHAR(1024) DEFAULT NULL,
  `StartDate` DATETIME DEFAULT NULL,
  `EndDate` DATETIME DEFAULT NULL,
  `DueDate` DATETIME DEFAULT NULL,
  `ObjectId1` INT DEFAULT NULL,
  `ObjectId2` INT DEFAULT NULL,
  `ObjectId3` INT DEFAULT NULL,
  `LastModified` DATETIME DEFAULT NULL,
  `IsDeleted` TINYINT DEFAULT NULL,
  `SortOrder` INT DEFAULT NULL,
  `Depth` INT DEFAULT NULL,
  `ToolId` INT DEFAULT NULL,
  `IsHidden` TINYINT DEFAULT NULL,
  `ResultId` INT DEFAULT NULL,
  `DeletedDate` DATETIME DEFAULT NULL,
  `CreatedBy` INT DEFAULT NULL,
  `LastModifiedBy` INT DEFAULT NULL,
  `DeletedBy` INT DEFAULT NULL,
  UNIQUE KEY (`ContentObjectId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
