DROP TABLE IF EXISTS `DiscussionForum_LOAD`;

CREATE TABLE `DiscussionForum_LOAD` (
  `OrgUnitId` INT DEFAULT NULL,
  `ForumId` BIGINT NOT NULL,
  `Name` VARCHAR(400) DEFAULT NULL,
  `Description` VARCHAR(1000) DEFAULT NULL,
  `MustPostToParticipate` TINYINT DEFAULT NULL,
  `AllowAnon` TINYINT DEFAULT NULL,
  `IsHidden` TINYINT DEFAULT NULL,
  `RequiresApproval` TINYINT DEFAULT NULL,
  `SortOrder` INT DEFAULT NULL,
  `IsDeleted` TINYINT DEFAULT NULL,
  `DeletedDate` DATETIME DEFAULT NULL,
  `DeletedByUserId` INT DEFAULT NULL,
  `ResultId` INT DEFAULT NULL,
  `StartDate` DATETIME DEFAULT NULL,
  `StartDateAvailabilityType` SMALLINT DEFAULT NULL,
  `EndDate` DATETIME DEFAULT NULL,
  `EndDateAvailabilityType` SMALLINT DEFAULT NULL,
  UNIQUE KEY (`ForumId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
