DROP TABLE IF EXISTS `SessionHistory_LOAD`;

CREATE TABLE `SessionHistory_LOAD` (
  `SessionId` BIGINT DEFAULT NULL,
  `OrgId` INT DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  `DateStarted` DATETIME DEFAULT NULL,
  `DateEnded` DATETIME DEFAULT NULL,
  `LastAccessed` DATETIME DEFAULT NULL,
  `TimedOut` TINYINT DEFAULT NULL,
  `HistoryID` BIGINT NOT NULL,
  UNIQUE KEY (`HistoryID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
