DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
  `UserId` INT NOT NULL,
  `UserName` VARCHAR(270) DEFAULT NULL,
  `OrgDefinedId` VARCHAR(256) DEFAULT NULL,
  `FirstName` VARCHAR(64) DEFAULT NULL,
  `MiddleName` VARCHAR(64) DEFAULT NULL,
  `LastName` VARCHAR(64) DEFAULT NULL,
  `IsActive` TINYINT DEFAULT NULL,
  `Organization` VARCHAR(256) DEFAULT NULL,
  `ExternalEmail` VARCHAR(256) DEFAULT NULL,
  `SignupDate` DATETIME DEFAULT NULL,
  `FirstLoginDate` DATETIME DEFAULT NULL,
  `Version` BIGINT DEFAULT NULL,
  `OrgRoleId` INT DEFAULT NULL,
  `LastAccessed` DATETIME DEFAULT NULL,
  UNIQUE KEY (`UserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
