DROP TABLE D2L_DISCUSSION_TOPIC;
CREATE TABLE D2L_DISCUSSION_TOPIC (
  OrgUnitId NUMBER(10) DEFAULT NULL,
  TopicId NUMBER(20) NOT NULL,
  ForumId NUMBER(20) DEFAULT NULL,
  Name NVARCHAR2(2000) DEFAULT NULL,
  Description NVARCHAR2(2000) DEFAULT NULL,
  MustPostToParticipate NUMBER(1) DEFAULT NULL,
  AllowAnon NUMBER(1) DEFAULT NULL,
  IsHidden NUMBER(1) DEFAULT NULL,
  RequiresApproval NUMBER(1) DEFAULT NULL,
  LastPostDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastPostUserId NUMBER(20) DEFAULT NULL,
  NumViews NUMBER(20) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  DeletedDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  DeletedByUserId NUMBER(10) DEFAULT NULL,
  GradeItemId NUMBER(10) DEFAULT NULL,
  ScoreOutOf FLOAT(53) DEFAULT NULL,
  ScoreCalculationMethod VARCHAR2(38 CHAR) DEFAULT NULL,
  IncludeNonScoredValues NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  ResultId NUMBER(10) DEFAULT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  StartDateAvailabilityType NUMBER(5) DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDateAvailabilityType NUMBER(5) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_DISCUSSION_TOPIC_PK ON D2L_DISCUSSION_TOPIC (TopicId);
QUIT;
