DROP TABLE D2L_ORGANIZATIONAL_UNIT_PARENT_LOAD;
CREATE TABLE D2L_ORGANIZATIONAL_UNIT_PARENT_LOAD (
  OrgUnitId NUMBER(10) NOT NULL,
  ParentOrgUnitId NUMBER(10) NOT NULL,
  RowVersion NUMBER(20) DEFAULT NULL,
  DateDeleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_PARENT_LOAD_PK ON D2L_ORGANIZATIONAL_UNIT_PARENT_LOAD (OrgUnitId,ParentOrgUnitId);
QUIT;
