DROP TABLE D2L_SURVEY_ATTEMPT;
CREATE TABLE D2L_SURVEY_ATTEMPT (
  AttemptId NUMBER(20) NOT NULL,
  SurveyId NUMBER(20) DEFAULT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  AttemptNumber NUMBER(10) DEFAULT NULL,
  TimeStarted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  TimeCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  AttemptedFromOrgUnitId NUMBER(10) DEFAULT NULL,
  OldAttemptNumber NUMBER(10) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_SURVEY_ATTEMPT_PK ON D2L_SURVEY_ATTEMPT (AttemptId);
QUIT;
