DROP TABLE D2L_INTELLIGENT_AGENT_RUN_LOG_LOAD;
CREATE TABLE D2L_INTELLIGENT_AGENT_RUN_LOG_LOAD (
  AgentId NUMBER(20) DEFAULT NULL,
  AgentRunId NUMBER(20) NOT NULL,
  IsPracticeRun NUMBER(1) DEFAULT NULL,
  IsRunNow NUMBER(1) DEFAULT NULL,
  NumUsers NUMBER(10) DEFAULT NULL,
  NumUsersWithErrors NUMBER(10) DEFAULT NULL,
  NumUsersWithInfos NUMBER(10) DEFAULT NULL,
  NumUsersWithWarnings NUMBER(10) DEFAULT NULL,
  RunUserId NUMBER(10) DEFAULT NULL,
  RunDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_INTELLIGENT_AGENT_RUN_LOG_LOAD_PK ON D2L_INTELLIGENT_AGENT_RUN_LOG_LOAD (AgentRunId);
QUIT;
