DROP TABLE D2L_ACTIVITY_EXEMPTION_LOG;
CREATE TABLE D2L_ACTIVITY_EXEMPTION_LOG (
  OrgUnitId NUMBER(10) DEFAULT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  ObjectId NUMBER(10) DEFAULT NULL,
  ActivityId VARCHAR2(450 CHAR) DEFAULT NULL,
  LogTypeName VARCHAR2(100 CHAR) DEFAULT NULL,
  LastModifiedUtc TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(10) DEFAULT NULL,
  ActivityExemptionsLogId NUMBER(20) NOT NULL,
  ToolId NUMBER(10) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ACTIVITY_EXEMPTION_LOG_PK ON D2L_ACTIVITY_EXEMPTION_LOG (ActivityExemptionsLogId);
QUIT;
