DROP TABLE D2L_CHAT_SESSION_LOG;
CREATE TABLE D2L_CHAT_SESSION_LOG (
  OrgUnitId NUMBER(10) DEFAULT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  ChatSessionId NUMBER(20) DEFAULT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  TimeSent TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  MessageId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_CHAT_SESSION_LOG_PK ON D2L_CHAT_SESSION_LOG (MessageId);
QUIT;
