DROP TABLE D2L_INTELLIGENT_AGENT_RUN_LOG;
CREATE TABLE D2L_INTELLIGENT_AGENT_RUN_LOG (
  AgentId NUMBER(20) DEFAULT NULL,
  AgentRunId NUMBER(20) NOT NULL,
  IsPracticeRun NUMBER(1) DEFAULT NULL,
  IsRunNow NUMBER(1) DEFAULT NULL,
  NumUsers NUMBER(10) DEFAULT NULL,
  NumUsersWithErrors NUMBER(10) DEFAULT NULL,
  NumUsersWithInfos NUMBER(10) DEFAULT NULL,
  NumUsersWithWarnings NUMBER(10) DEFAULT NULL,
  RunUserId NUMBER(10) DEFAULT NULL,
  RunDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_INTELLIGENT_AGENT_RUN_LOG_PK ON D2L_INTELLIGENT_AGENT_RUN_LOG (AgentRunId);
QUIT;
