DROP TABLE D2L_QUESTION_RELATIONSHIP;
CREATE TABLE D2L_QUESTION_RELATIONSHIP (
  CollectionId NUMBER(20) DEFAULT NULL,
  QuestionId NUMBER(20) DEFAULT NULL,
  QuestionVersionId NUMBER(20) DEFAULT NULL,
  D2LOrder NUMBER(20) DEFAULT NULL,
  SectionId NUMBER(20) DEFAULT NULL,
  IsQuestionPool NUMBER(1) DEFAULT NULL,
  CreationDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  CreatedBy NUMBER(20) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModifiedBy NUMBER(20) DEFAULT NULL,
  Points DECIMAL(19, 9) DEFAULT NULL,
  Difficulty NUMBER(10) DEFAULT NULL,
  IsBonus NUMBER(1) DEFAULT NULL,
  IsMandatory NUMBER(1) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL,
  ObjectId NUMBER(20) DEFAULT NULL
);
QUIT;
