DROP TABLE D2L_ATTENDANCE_SESSION_LOAD;
CREATE TABLE D2L_ATTENDANCE_SESSION_LOAD (
  AttendanceSessionId NUMBER(20) NOT NULL,
  AttendanceRegisterId NUMBER(20) DEFAULT NULL,
  Name NVARCHAR2(256) DEFAULT NULL,
  Description NVARCHAR2(512) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  Version NUMBER(20) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_ATTENDANCE_SESSION_LOAD_PK ON D2L_ATTENDANCE_SESSION_LOAD (AttendanceSessionId);
QUIT;
