DROP TABLE D2L_COURSE_PUBLISHER_LAUNCH;
CREATE TABLE D2L_COURSE_PUBLISHER_LAUNCH (
  LaunchId VARCHAR2(36) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  RecipientId VARCHAR2(36) DEFAULT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  RoleId NUMBER(10) DEFAULT NULL,
  LaunchMethod NVARCHAR2(512) DEFAULT NULL,
  ExternalUserId NVARCHAR2(512) DEFAULT NULL,
  ExternalLMSType NVARCHAR2(512) DEFAULT NULL,
  IsNewUser NUMBER(1) DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_COURSE_PUBLISHER_LAUNCH_PK ON D2L_COURSE_PUBLISHER_LAUNCH (LaunchId);
QUIT;
