DROP TABLE D2L_RUBRIC_OBJECT_CRITERIA;
CREATE TABLE D2L_RUBRIC_OBJECT_CRITERIA (
  RubricId NUMBER(20) DEFAULT NULL,
  CriterionId NUMBER(20) NOT NULL,
  Name NVARCHAR2(512) DEFAULT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  CriteriaGroupId NUMBER(20) DEFAULT NULL,
  GroupName NVARCHAR2(512) DEFAULT NULL,
  GroupSortOrder NUMBER(10) DEFAULT NULL,
  LevelSetId NUMBER(20) DEFAULT NULL,
  IsDeleted NUMBER(1) DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_RUBRIC_OBJECT_CRITERIA_PK ON D2L_RUBRIC_OBJECT_CRITERIA (CriterionId);
QUIT;
