DROP TABLE D2L_CHECKLIST_COMPLETION_LOAD;
CREATE TABLE D2L_CHECKLIST_COMPLETION_LOAD (
  UserId NUMBER(10) NOT NULL,
  DateCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  ItemId NUMBER(20) NOT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CHECKLIST_COMPLETION_LOAD_PK ON D2L_CHECKLIST_COMPLETION_LOAD (UserId,ItemId);
QUIT;
