DROP TABLE D2L_LOCAL_AUTHENTICATION_SECURITY_LOG_LOAD;
CREATE TABLE D2L_LOCAL_AUTHENTICATION_SECURITY_LOG_LOAD (
  UserId NUMBER(10) NOT NULL,
  Action NVARCHAR2(140) NOT NULL,
  ModifiedBy NUMBER(10) NOT NULL,
  ModifiedDate TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX D2L_LOCAL_AUTHENTICATION_SECURITY_LOG_LOAD_PK ON D2L_LOCAL_AUTHENTICATION_SECURITY_LOG_LOAD (UserId,Action,ModifiedBy,ModifiedDate);
QUIT;
