DROP TABLE D2L_CHAT_SESSION_LOG_LOAD;
CREATE TABLE D2L_CHAT_SESSION_LOG_LOAD (
  OrgUnitId NUMBER(10) DEFAULT NULL,
  UserId NUMBER(10) DEFAULT NULL,
  ChatSessionId NUMBER(20) DEFAULT NULL,
  StartDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  EndDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  TimeSent TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  MessageId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_CHAT_SESSION_LOG_LOAD_PK ON D2L_CHAT_SESSION_LOG_LOAD (MessageId);
QUIT;
