DROP TABLE D2L_ORGANIZATIONAL_UNIT_DESCENDANT;
CREATE TABLE D2L_ORGANIZATIONAL_UNIT_DESCENDANT (
  OrgUnitId NUMBER(10) NOT NULL,
  DescendantOrgUnitId NUMBER(10) NOT NULL
);
CREATE UNIQUE INDEX D2L_ORGANIZATIONAL_UNIT_DESCENDANT_PK ON D2L_ORGANIZATIONAL_UNIT_DESCENDANT (OrgUnitId,DescendantOrgUnitId);
QUIT;
