DROP TABLE D2L_TURNITIN_SUBMISSION;
CREATE TABLE D2L_TURNITIN_SUBMISSION (
  DropboxId NUMBER(20) DEFAULT NULL,
  SubmissionId NUMBER(20) NOT NULL,
  FileId NUMBER(20) NOT NULL,
  LastSubmissionDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  SubmissionStatus NUMBER(5) DEFAULT NULL,
  SubmissionErrorType NUMBER(5) DEFAULT NULL,
  ErrorMessage NVARCHAR2(510) DEFAULT NULL,
  SubmittedBy NUMBER(10) DEFAULT NULL,
  LastRefreshDate TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_TURNITIN_SUBMISSION_PK ON D2L_TURNITIN_SUBMISSION (SubmissionId,FileId);
QUIT;
