DROP TABLE D2L_CONTENT_USER_COMPLETION;
CREATE TABLE D2L_CONTENT_USER_COMPLETION (
  ContentObjectId NUMBER(10) NOT NULL,
  OrgUnitId NUMBER(10) DEFAULT NULL,
  UserId NUMBER(10) NOT NULL,
  DateCompleted TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL,
  LastModified TIMESTAMP WITH LOCAL TIME ZONE DEFAULT NULL
);
CREATE UNIQUE INDEX D2L_CONTENT_USER_COMPLETION_PK ON D2L_CONTENT_USER_COMPLETION (ContentObjectId,UserId);
QUIT;
