DROP TABLE D2L_QUIZ_QUESTION_ANSWER_LOAD;
CREATE TABLE D2L_QUIZ_QUESTION_ANSWER_LOAD (
  AnswerId NUMBER(20) NOT NULL,
  QuestionId NUMBER(20) NOT NULL,
  QuestionVersionId NUMBER(20) NOT NULL,
  SortOrder NUMBER(10) DEFAULT NULL,
  IsCorrect NUMBER(1) DEFAULT NULL,
  Weight DECIMAL(19, 9) DEFAULT NULL,
  Answer NVARCHAR2(2000) DEFAULT NULL,
  D2LComment NVARCHAR2(2000) DEFAULT NULL,
  Description NVARCHAR2(512) DEFAULT NULL,
  ObjectId NUMBER(20) NOT NULL
);
CREATE UNIQUE INDEX D2L_QUIZ_QUESTION_ANSWER_LOAD_PK ON D2L_QUIZ_QUESTION_ANSWER_LOAD (AnswerId,QuestionId,QuestionVersionId,ObjectId);
QUIT;
