DROP TABLE IF EXISTS `ActivityFeedPostLog_LOAD`;

CREATE TABLE `ActivityFeedPostLog_LOAD` (
  `LogId` VARCHAR(16) NOT NULL,
  `UserId` INT DEFAULT NULL,
  `OrgUnitId` INT DEFAULT NULL,
  `PostId` VARCHAR(16) DEFAULT NULL,
  `PostType` VARCHAR(16) DEFAULT NULL,
  `Action` VARCHAR(16) DEFAULT NULL,
  `ActionDate` DATETIME DEFAULT NULL,
  `DropboxId` BIGINT DEFAULT NULL,
  `Content` VARCHAR(3072) DEFAULT NULL,
  `CommentCount` INT DEFAULT NULL,
  `AttachmentCount` INT DEFAULT NULL,
  UNIQUE KEY (`LogId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
