DROP TABLE IF EXISTS `ActivityFeedCommentLog`;

CREATE TABLE `ActivityFeedCommentLog` (
  `LogId` VARCHAR(16) NOT NULL,
  `UserId` INT DEFAULT NULL,
  `OrgUnitId` INT DEFAULT NULL,
  `CommentId` VARCHAR(16) DEFAULT NULL,
  `Action` VARCHAR(16) DEFAULT NULL,
  `ActionDate` DATETIME DEFAULT NULL,
  `Content` VARCHAR(3072) DEFAULT NULL,
  `PostId` VARCHAR(16) DEFAULT NULL,
  UNIQUE KEY (`LogId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

