DROP TABLE IF EXISTS `AwardObject`;

CREATE TABLE `AwardObject` (
  `AwardId` BIGINT NOT NULL,
  `Name` VARCHAR(256) DEFAULT NULL,
  `AwardTypeId` INT DEFAULT NULL,
  `Type` VARCHAR(128) DEFAULT NULL,
  `Description` VARCHAR(512) DEFAULT NULL,
  `ExpiryCalculationType` VARCHAR(128) DEFAULT NULL,
  `ExpiryNotificationType` VARCHAR(128) DEFAULT NULL,
  `ExpiryDate` DATETIME DEFAULT NULL,
  `ImagePath` VARCHAR(1000) DEFAULT NULL,
  `CreatedByUserId` BIGINT DEFAULT NULL,
  `LastModified` DATETIME DEFAULT NULL,
  `IsDeleted` TINYINT DEFAULT NULL,
  `Criteria` VARCHAR(1000) DEFAULT NULL,
  UNIQUE KEY (`AwardId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

