DROP TABLE IF EXISTS `DiscussionPost`;

CREATE TABLE `DiscussionPost` (
  `OrgUnitId` INT DEFAULT NULL,
  `TopicId` BIGINT DEFAULT NULL,
  `UserId` INT DEFAULT NULL,
  `PostId` BIGINT NOT NULL,
  `ThreadId` BIGINT DEFAULT NULL,
  `IsReply` TINYINT DEFAULT NULL,
  `ParentPostId` BIGINT DEFAULT NULL,
  `NumReplies` INT DEFAULT NULL,
  `DatePosted` DATETIME DEFAULT NULL,
  `IsDeleted` TINYINT DEFAULT NULL,
  `RatingSum` BIGINT DEFAULT NULL,
  `NumRatings` BIGINT DEFAULT NULL,
  `Score` DECIMAL(19, 9) DEFAULT NULL,
  `LastEditDate` DATETIME DEFAULT NULL,
  `SortOrder` INT DEFAULT NULL,
  `Depth` INT DEFAULT NULL,
  `Thread` VARCHAR(400) DEFAULT NULL,
  `WordCount` INT DEFAULT NULL,
  `AttachmentCount` INT DEFAULT NULL,
  UNIQUE KEY (`PostId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

