DROP TABLE IF EXISTS `QuizObject`;

CREATE TABLE `QuizObject` (
  `QuizId` BIGINT NOT NULL,
  `QuizName` VARCHAR(256) NOT NULL,
  `QuizDescription` VARCHAR(1000) DEFAULT NULL,
  `QuizCategory` VARCHAR(256) DEFAULT NULL,
  `IsActive` TINYINT NOT NULL,
  `OrgUnitId` INT NOT NULL,
  `StartDate` DATETIME DEFAULT NULL,
  `EndDate` DATETIME DEFAULT NULL,
  `DueDate` DATETIME DEFAULT NULL,
  `CreationDate` DATETIME NOT NULL,
  `CreatedBy` BIGINT DEFAULT NULL,
  `LastModified` DATETIME NOT NULL,
  `LastModifiedBy` BIGINT DEFAULT NULL,
  `GradeObjectId` BIGINT DEFAULT NULL,
  `OverallScoreCalculation` VARCHAR(23) DEFAULT NULL,
  `QuizScoreDenominator` DECIMAL(19, 9) NOT NULL,
  `HasPassword` TINYINT DEFAULT NULL,
  `IPRestricted` TINYINT DEFAULT NULL,
  `TimeLimit` INT NOT NULL,
  `TimeLimitEnforced` TINYINT NOT NULL,
  `TimeLimitExceededBehavior` INT DEFAULT NULL,
  `TimeLimitGracePeriod` INT DEFAULT NULL,
  `AttemptsAllowed` INT DEFAULT NULL,
  `PreventMovingBackwards` TINYINT NOT NULL,
  `AllowHints` TINYINT NOT NULL,
  `NotificationEmail` VARCHAR(1000) DEFAULT NULL,
  `DisablePagerAccess` TINYINT NOT NULL,
  `DisplayInCalendar` TINYINT DEFAULT NULL,
  `ShowClock` TINYINT NOT NULL,
  `IsAttemptRldb` TINYINT NOT NULL,
  `IsSubviewRldb` TINYINT NOT NULL,
  `SortOrder` INT NOT NULL,
  `CategoryId` BIGINT DEFAULT NULL,
  `ResultId` BIGINT DEFAULT NULL,
  `IsRetakeIncorrectOnly` TINYINT NOT NULL,
  `PagingTypeId` INT DEFAULT NULL,
  UNIQUE KEY (`QuizId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
