DROP TABLE IF EXISTS `RoleDetail`;

CREATE TABLE `RoleDetail` (
  `RoleId` INT NOT NULL,
  `OrgId` INT DEFAULT NULL,
  `RoleName` VARCHAR(60) NOT NULL,
  `Description` VARCHAR(200) DEFAULT NULL,
  `IsCascading` TINYINT NOT NULL,
  `InClassList` TINYINT NOT NULL,
  `ClassListRoleName` VARCHAR(60) DEFAULT NULL,
  `ClassListShowGroups` TINYINT NOT NULL,
  `ClassListShowSections` TINYINT NOT NULL,
  `ClassListDisplayRole` TINYINT NOT NULL,
  `AccessInactiveCO` TINYINT NOT NULL,
  `HasSpecialAccess` TINYINT NOT NULL,
  `AddToCourseOfferingGroups` TINYINT NOT NULL,
  `CanBeAutoEnrolledIntoGroups` TINYINT NOT NULL,
  `AddToCourseOfferingSections` TINYINT NOT NULL,
  `CanBeAutoEnrolledIntoSections` TINYINT NOT NULL,
  `ClassListDisplayRoleCategory` TINYINT NOT NULL,
  `ClassListRoleCategory` VARCHAR(50) NOT NULL,
  `ClassListRoleCategoryOrder` INT NOT NULL,
  `AccessPastCourses` TINYINT NOT NULL,
  `AccessFutureCourses` TINYINT NOT NULL,
  `SortOrder` INT NOT NULL,
  `ShowInContent` TINYINT NOT NULL,
  `ShowInDiscussionAssess` TINYINT NOT NULL,
  `ShowInDiscussionStats` TINYINT NOT NULL,
  `ShowInGrades` TINYINT NOT NULL,
  `ShowInAttendance` TINYINT NOT NULL,
  `AllowSelfEnrollInGroups` TINYINT NOT NULL,
  `ShowInRegistration` TINYINT NOT NULL,
  `ShowInUserProgress` TINYINT NOT NULL,
  `RoleAlias` VARCHAR(60) DEFAULT NULL,
  `Version` BIGINT NOT NULL,
  `RoleCode` VARCHAR(50) DEFAULT NULL,
  UNIQUE KEY (`RoleId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
