DROP TABLE IF EXISTS `SCORMObjective_LOAD`;

CREATE TABLE `SCORMObjective_LOAD` (
  `ObjectiveId` VARCHAR(36) NOT NULL,
  `ScormObjectId` VARCHAR(36) DEFAULT NULL,
  `ObjectiveType` VARCHAR(100) DEFAULT NULL,
  `ActivityId` VARCHAR(36) DEFAULT NULL,
  `InternalId` VARCHAR(255) DEFAULT NULL,
  `IsPrimary` TINYINT DEFAULT NULL,
  `Description` VARCHAR(250) DEFAULT NULL,
  `ScoreMin` FLOAT DEFAULT NULL,
  `ScoreMax` FLOAT DEFAULT NULL,
  `LastModified` DATETIME DEFAULT NULL,
  UNIQUE KEY (`ObjectiveId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
